/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.automatic.webui.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * MemoryResponse
 */
@JsonPropertyOrder({
  MemoryResponse.JSON_PROPERTY_RAM,
  MemoryResponse.JSON_PROPERTY_CUDA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-27T01:31:55.639766089+03:00[Europe/Moscow]")
public class MemoryResponse {
  public static final String JSON_PROPERTY_RAM = "ram";
  private Object ram;

  public static final String JSON_PROPERTY_CUDA = "cuda";
  private Object cuda;

  public MemoryResponse() {
  }

  public MemoryResponse ram(Object ram) {
    
    this.ram = ram;
    return this;
  }

   /**
   * System memory stats
   * @return ram
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RAM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getRam() {
    return ram;
  }


  @JsonProperty(JSON_PROPERTY_RAM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRam(Object ram) {
    this.ram = ram;
  }


  public MemoryResponse cuda(Object cuda) {
    
    this.cuda = cuda;
    return this;
  }

   /**
   * nVidia CUDA memory stats
   * @return cuda
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CUDA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getCuda() {
    return cuda;
  }


  @JsonProperty(JSON_PROPERTY_CUDA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCuda(Object cuda) {
    this.cuda = cuda;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MemoryResponse memoryResponse = (MemoryResponse) o;
    return Objects.equals(this.ram, memoryResponse.ram) &&
        Objects.equals(this.cuda, memoryResponse.cuda);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ram, cuda);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MemoryResponse {\n");
    sb.append("    ram: ").append(toIndentedString(ram)).append("\n");
    sb.append("    cuda: ").append(toIndentedString(cuda)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

