/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.automatic.webui.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ModulesApiModelsProgressResponse
 */
@JsonPropertyOrder({
  ModulesApiModelsProgressResponse.JSON_PROPERTY_PROGRESS,
  ModulesApiModelsProgressResponse.JSON_PROPERTY_ETA_RELATIVE,
  ModulesApiModelsProgressResponse.JSON_PROPERTY_STATE,
  ModulesApiModelsProgressResponse.JSON_PROPERTY_CURRENT_IMAGE,
  ModulesApiModelsProgressResponse.JSON_PROPERTY_TEXTINFO
})
@JsonTypeName("modules__api__models__ProgressResponse")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-27T02:28:26.857180667+03:00[Europe/Moscow]")
public class ModulesApiModelsProgressResponse {
  public static final String JSON_PROPERTY_PROGRESS = "progress";
  private BigDecimal progress;

  public static final String JSON_PROPERTY_ETA_RELATIVE = "eta_relative";
  private BigDecimal etaRelative;

  public static final String JSON_PROPERTY_STATE = "state";
  private Object state;

  public static final String JSON_PROPERTY_CURRENT_IMAGE = "current_image";
  private String currentImage;

  public static final String JSON_PROPERTY_TEXTINFO = "textinfo";
  private String textinfo;

  public ModulesApiModelsProgressResponse() {
  }

  public ModulesApiModelsProgressResponse progress(BigDecimal progress) {
    
    this.progress = progress;
    return this;
  }

   /**
   * The progress with a range of 0 to 1
   * @return progress
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROGRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getProgress() {
    return progress;
  }


  @JsonProperty(JSON_PROPERTY_PROGRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProgress(BigDecimal progress) {
    this.progress = progress;
  }


  public ModulesApiModelsProgressResponse etaRelative(BigDecimal etaRelative) {
    
    this.etaRelative = etaRelative;
    return this;
  }

   /**
   * Get etaRelative
   * @return etaRelative
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ETA_RELATIVE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getEtaRelative() {
    return etaRelative;
  }


  @JsonProperty(JSON_PROPERTY_ETA_RELATIVE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEtaRelative(BigDecimal etaRelative) {
    this.etaRelative = etaRelative;
  }


  public ModulesApiModelsProgressResponse state(Object state) {
    
    this.state = state;
    return this;
  }

   /**
   * The current state snapshot
   * @return state
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setState(Object state) {
    this.state = state;
  }


  public ModulesApiModelsProgressResponse currentImage(String currentImage) {
    
    this.currentImage = currentImage;
    return this;
  }

   /**
   * The current image in base64 format. opts.show_progress_every_n_steps is required for this to work.
   * @return currentImage
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENT_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrentImage() {
    return currentImage;
  }


  @JsonProperty(JSON_PROPERTY_CURRENT_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrentImage(String currentImage) {
    this.currentImage = currentImage;
  }


  public ModulesApiModelsProgressResponse textinfo(String textinfo) {
    
    this.textinfo = textinfo;
    return this;
  }

   /**
   * Info text used by WebUI.
   * @return textinfo
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEXTINFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTextinfo() {
    return textinfo;
  }


  @JsonProperty(JSON_PROPERTY_TEXTINFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextinfo(String textinfo) {
    this.textinfo = textinfo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModulesApiModelsProgressResponse modulesApiModelsProgressResponse = (ModulesApiModelsProgressResponse) o;
    return Objects.equals(this.progress, modulesApiModelsProgressResponse.progress) &&
        Objects.equals(this.etaRelative, modulesApiModelsProgressResponse.etaRelative) &&
        Objects.equals(this.state, modulesApiModelsProgressResponse.state) &&
        Objects.equals(this.currentImage, modulesApiModelsProgressResponse.currentImage) &&
        Objects.equals(this.textinfo, modulesApiModelsProgressResponse.textinfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(progress, etaRelative, state, currentImage, textinfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModulesApiModelsProgressResponse {\n");
    sb.append("    progress: ").append(toIndentedString(progress)).append("\n");
    sb.append("    etaRelative: ").append(toIndentedString(etaRelative)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    currentImage: ").append(toIndentedString(currentImage)).append("\n");
    sb.append("    textinfo: ").append(toIndentedString(textinfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

