/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.automatic.webui.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ResetBody
 */
@JsonPropertyOrder({
  ResetBody.JSON_PROPERTY_SESSION_HASH,
  ResetBody.JSON_PROPERTY_FN_INDEX
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-27T01:31:55.639766089+03:00[Europe/Moscow]")
public class ResetBody {
  public static final String JSON_PROPERTY_SESSION_HASH = "session_hash";
  private String sessionHash;

  public static final String JSON_PROPERTY_FN_INDEX = "fn_index";
  private Integer fnIndex;

  public ResetBody() {
  }

  public ResetBody sessionHash(String sessionHash) {
    
    this.sessionHash = sessionHash;
    return this;
  }

   /**
   * Get sessionHash
   * @return sessionHash
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SESSION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSessionHash() {
    return sessionHash;
  }


  @JsonProperty(JSON_PROPERTY_SESSION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSessionHash(String sessionHash) {
    this.sessionHash = sessionHash;
  }


  public ResetBody fnIndex(Integer fnIndex) {
    
    this.fnIndex = fnIndex;
    return this;
  }

   /**
   * Get fnIndex
   * @return fnIndex
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FN_INDEX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getFnIndex() {
    return fnIndex;
  }


  @JsonProperty(JSON_PROPERTY_FN_INDEX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFnIndex(Integer fnIndex) {
    this.fnIndex = fnIndex;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResetBody resetBody = (ResetBody) o;
    return Objects.equals(this.sessionHash, resetBody.sessionHash) &&
        Objects.equals(this.fnIndex, resetBody.fnIndex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessionHash, fnIndex);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResetBody {\n");
    sb.append("    sessionHash: ").append(toIndentedString(sessionHash)).append("\n");
    sb.append("    fnIndex: ").append(toIndentedString(fnIndex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

