/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.automatic.webui.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ScriptsList
 */
@JsonPropertyOrder({
  ScriptsList.JSON_PROPERTY_TXT2IMG,
  ScriptsList.JSON_PROPERTY_IMG2IMG
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-27T02:28:26.857180667+03:00[Europe/Moscow]")
public class ScriptsList {
  public static final String JSON_PROPERTY_TXT2IMG = "txt2img";
  private List<Object> txt2img;

  public static final String JSON_PROPERTY_IMG2IMG = "img2img";
  private List<Object> img2img;

  public ScriptsList() {
  }

  public ScriptsList txt2img(List<Object> txt2img) {
    
    this.txt2img = txt2img;
    return this;
  }

  public ScriptsList addTxt2imgItem(Object txt2imgItem) {
    if (this.txt2img == null) {
      this.txt2img = new ArrayList<>();
    }
    this.txt2img.add(txt2imgItem);
    return this;
  }

   /**
   * Titles of scripts (txt2img)
   * @return txt2img
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TXT2IMG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getTxt2img() {
    return txt2img;
  }


  @JsonProperty(JSON_PROPERTY_TXT2IMG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTxt2img(List<Object> txt2img) {
    this.txt2img = txt2img;
  }


  public ScriptsList img2img(List<Object> img2img) {
    
    this.img2img = img2img;
    return this;
  }

  public ScriptsList addImg2imgItem(Object img2imgItem) {
    if (this.img2img == null) {
      this.img2img = new ArrayList<>();
    }
    this.img2img.add(img2imgItem);
    return this;
  }

   /**
   * Titles of scripts (img2img)
   * @return img2img
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IMG2IMG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getImg2img() {
    return img2img;
  }


  @JsonProperty(JSON_PROPERTY_IMG2IMG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImg2img(List<Object> img2img) {
    this.img2img = img2img;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScriptsList scriptsList = (ScriptsList) o;
    return Objects.equals(this.txt2img, scriptsList.txt2img) &&
        Objects.equals(this.img2img, scriptsList.img2img);
  }

  @Override
  public int hashCode() {
    return Objects.hash(txt2img, img2img);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScriptsList {\n");
    sb.append("    txt2img: ").append(toIndentedString(txt2img)).append("\n");
    sb.append("    img2img: ").append(toIndentedString(img2img)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

