/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.automatic.webui.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * StableDiffusionProcessingTxt2Img
 */
@JsonPropertyOrder({
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_PROMPT,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_NEGATIVE_PROMPT,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_STYLES,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_SEED,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_SUBSEED,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_SUBSEED_STRENGTH,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_SEED_RESIZE_FROM_H,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_SEED_RESIZE_FROM_W,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_SAMPLER_NAME,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_BATCH_SIZE,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_N_ITER,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_STEPS,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_CFG_SCALE,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_WIDTH,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_HEIGHT,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_RESTORE_FACES,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_TILING,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_DO_NOT_SAVE_SAMPLES,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_DO_NOT_SAVE_GRID,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_ETA,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_DENOISING_STRENGTH,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_S_MIN_UNCOND,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_S_CHURN,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_S_TMAX,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_S_TMIN,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_S_NOISE,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_OVERRIDE_SETTINGS,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_OVERRIDE_SETTINGS_RESTORE_AFTERWARDS,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_REFINER_CHECKPOINT,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_REFINER_SWITCH_AT,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_DISABLE_EXTRA_NETWORKS,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_COMMENTS,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_ENABLE_HR,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_FIRSTPHASE_WIDTH,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_FIRSTPHASE_HEIGHT,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_HR_SCALE,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_HR_UPSCALER,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_HR_SECOND_PASS_STEPS,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_HR_RESIZE_X,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_HR_RESIZE_Y,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_HR_CHECKPOINT_NAME,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_HR_SAMPLER_NAME,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_HR_PROMPT,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_HR_NEGATIVE_PROMPT,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_SAMPLER_INDEX,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_SCRIPT_NAME,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_SCRIPT_ARGS,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_SEND_IMAGES,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_SAVE_IMAGES,
  StableDiffusionProcessingTxt2Img.JSON_PROPERTY_ALWAYSON_SCRIPTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-27T01:31:55.639766089+03:00[Europe/Moscow]")
public class StableDiffusionProcessingTxt2Img {
  public static final String JSON_PROPERTY_PROMPT = "prompt";
  private String prompt = "";

  public static final String JSON_PROPERTY_NEGATIVE_PROMPT = "negative_prompt";
  private String negativePrompt = "";

  public static final String JSON_PROPERTY_STYLES = "styles";
  private List<String> styles;

  public static final String JSON_PROPERTY_SEED = "seed";
  private Integer seed = -1;

  public static final String JSON_PROPERTY_SUBSEED = "subseed";
  private Integer subseed = -1;

  public static final String JSON_PROPERTY_SUBSEED_STRENGTH = "subseed_strength";
  private BigDecimal subseedStrength = new BigDecimal("0");

  public static final String JSON_PROPERTY_SEED_RESIZE_FROM_H = "seed_resize_from_h";
  private Integer seedResizeFromH = -1;

  public static final String JSON_PROPERTY_SEED_RESIZE_FROM_W = "seed_resize_from_w";
  private Integer seedResizeFromW = -1;

  public static final String JSON_PROPERTY_SAMPLER_NAME = "sampler_name";
  private String samplerName;

  public static final String JSON_PROPERTY_BATCH_SIZE = "batch_size";
  private Integer batchSize = 1;

  public static final String JSON_PROPERTY_N_ITER = "n_iter";
  private Integer nIter = 1;

  public static final String JSON_PROPERTY_STEPS = "steps";
  private Integer steps = 50;

  public static final String JSON_PROPERTY_CFG_SCALE = "cfg_scale";
  private BigDecimal cfgScale = new BigDecimal("7.0");

  public static final String JSON_PROPERTY_WIDTH = "width";
  private Integer width = 512;

  public static final String JSON_PROPERTY_HEIGHT = "height";
  private Integer height = 512;

  public static final String JSON_PROPERTY_RESTORE_FACES = "restore_faces";
  private Boolean restoreFaces;

  public static final String JSON_PROPERTY_TILING = "tiling";
  private Boolean tiling;

  public static final String JSON_PROPERTY_DO_NOT_SAVE_SAMPLES = "do_not_save_samples";
  private Boolean doNotSaveSamples = false;

  public static final String JSON_PROPERTY_DO_NOT_SAVE_GRID = "do_not_save_grid";
  private Boolean doNotSaveGrid = false;

  public static final String JSON_PROPERTY_ETA = "eta";
  private BigDecimal eta;

  public static final String JSON_PROPERTY_DENOISING_STRENGTH = "denoising_strength";
  private BigDecimal denoisingStrength = new BigDecimal("0");

  public static final String JSON_PROPERTY_S_MIN_UNCOND = "s_min_uncond";
  private BigDecimal sMinUncond;

  public static final String JSON_PROPERTY_S_CHURN = "s_churn";
  private BigDecimal sChurn;

  public static final String JSON_PROPERTY_S_TMAX = "s_tmax";
  private BigDecimal sTmax;

  public static final String JSON_PROPERTY_S_TMIN = "s_tmin";
  private BigDecimal sTmin;

  public static final String JSON_PROPERTY_S_NOISE = "s_noise";
  private BigDecimal sNoise;

  public static final String JSON_PROPERTY_OVERRIDE_SETTINGS = "override_settings";
  private Object overrideSettings;

  public static final String JSON_PROPERTY_OVERRIDE_SETTINGS_RESTORE_AFTERWARDS = "override_settings_restore_afterwards";
  private Boolean overrideSettingsRestoreAfterwards = true;

  public static final String JSON_PROPERTY_REFINER_CHECKPOINT = "refiner_checkpoint";
  private String refinerCheckpoint;

  public static final String JSON_PROPERTY_REFINER_SWITCH_AT = "refiner_switch_at";
  private BigDecimal refinerSwitchAt;

  public static final String JSON_PROPERTY_DISABLE_EXTRA_NETWORKS = "disable_extra_networks";
  private Boolean disableExtraNetworks = false;

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  private Object comments;

  public static final String JSON_PROPERTY_ENABLE_HR = "enable_hr";
  private Boolean enableHr = false;

  public static final String JSON_PROPERTY_FIRSTPHASE_WIDTH = "firstphase_width";
  private Integer firstphaseWidth = 0;

  public static final String JSON_PROPERTY_FIRSTPHASE_HEIGHT = "firstphase_height";
  private Integer firstphaseHeight = 0;

  public static final String JSON_PROPERTY_HR_SCALE = "hr_scale";
  private BigDecimal hrScale = new BigDecimal("2.0");

  public static final String JSON_PROPERTY_HR_UPSCALER = "hr_upscaler";
  private String hrUpscaler;

  public static final String JSON_PROPERTY_HR_SECOND_PASS_STEPS = "hr_second_pass_steps";
  private Integer hrSecondPassSteps = 0;

  public static final String JSON_PROPERTY_HR_RESIZE_X = "hr_resize_x";
  private Integer hrResizeX = 0;

  public static final String JSON_PROPERTY_HR_RESIZE_Y = "hr_resize_y";
  private Integer hrResizeY = 0;

  public static final String JSON_PROPERTY_HR_CHECKPOINT_NAME = "hr_checkpoint_name";
  private String hrCheckpointName;

  public static final String JSON_PROPERTY_HR_SAMPLER_NAME = "hr_sampler_name";
  private String hrSamplerName;

  public static final String JSON_PROPERTY_HR_PROMPT = "hr_prompt";
  private String hrPrompt = "";

  public static final String JSON_PROPERTY_HR_NEGATIVE_PROMPT = "hr_negative_prompt";
  private String hrNegativePrompt = "";

  public static final String JSON_PROPERTY_SAMPLER_INDEX = "sampler_index";
  private String samplerIndex = "Euler";

  public static final String JSON_PROPERTY_SCRIPT_NAME = "script_name";
  private String scriptName;

  public static final String JSON_PROPERTY_SCRIPT_ARGS = "script_args";
  private List<Object> scriptArgs = new ArrayList<>();

  public static final String JSON_PROPERTY_SEND_IMAGES = "send_images";
  private Boolean sendImages = true;

  public static final String JSON_PROPERTY_SAVE_IMAGES = "save_images";
  private Boolean saveImages = false;

  public static final String JSON_PROPERTY_ALWAYSON_SCRIPTS = "alwayson_scripts";
  private Object alwaysonScripts = {};

  public StableDiffusionProcessingTxt2Img() {
  }

  public StableDiffusionProcessingTxt2Img prompt(String prompt) {
    
    this.prompt = prompt;
    return this;
  }

   /**
   * Get prompt
   * @return prompt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROMPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPrompt() {
    return prompt;
  }


  @JsonProperty(JSON_PROPERTY_PROMPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrompt(String prompt) {
    this.prompt = prompt;
  }


  public StableDiffusionProcessingTxt2Img negativePrompt(String negativePrompt) {
    
    this.negativePrompt = negativePrompt;
    return this;
  }

   /**
   * Get negativePrompt
   * @return negativePrompt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEGATIVE_PROMPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNegativePrompt() {
    return negativePrompt;
  }


  @JsonProperty(JSON_PROPERTY_NEGATIVE_PROMPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNegativePrompt(String negativePrompt) {
    this.negativePrompt = negativePrompt;
  }


  public StableDiffusionProcessingTxt2Img styles(List<String> styles) {
    
    this.styles = styles;
    return this;
  }

  public StableDiffusionProcessingTxt2Img addStylesItem(String stylesItem) {
    if (this.styles == null) {
      this.styles = new ArrayList<>();
    }
    this.styles.add(stylesItem);
    return this;
  }

   /**
   * Get styles
   * @return styles
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STYLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getStyles() {
    return styles;
  }


  @JsonProperty(JSON_PROPERTY_STYLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStyles(List<String> styles) {
    this.styles = styles;
  }


  public StableDiffusionProcessingTxt2Img seed(Integer seed) {
    
    this.seed = seed;
    return this;
  }

   /**
   * Get seed
   * @return seed
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSeed() {
    return seed;
  }


  @JsonProperty(JSON_PROPERTY_SEED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeed(Integer seed) {
    this.seed = seed;
  }


  public StableDiffusionProcessingTxt2Img subseed(Integer subseed) {
    
    this.subseed = subseed;
    return this;
  }

   /**
   * Get subseed
   * @return subseed
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUBSEED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSubseed() {
    return subseed;
  }


  @JsonProperty(JSON_PROPERTY_SUBSEED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubseed(Integer subseed) {
    this.subseed = subseed;
  }


  public StableDiffusionProcessingTxt2Img subseedStrength(BigDecimal subseedStrength) {
    
    this.subseedStrength = subseedStrength;
    return this;
  }

   /**
   * Get subseedStrength
   * @return subseedStrength
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUBSEED_STRENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getSubseedStrength() {
    return subseedStrength;
  }


  @JsonProperty(JSON_PROPERTY_SUBSEED_STRENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubseedStrength(BigDecimal subseedStrength) {
    this.subseedStrength = subseedStrength;
  }


  public StableDiffusionProcessingTxt2Img seedResizeFromH(Integer seedResizeFromH) {
    
    this.seedResizeFromH = seedResizeFromH;
    return this;
  }

   /**
   * Get seedResizeFromH
   * @return seedResizeFromH
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEED_RESIZE_FROM_H)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSeedResizeFromH() {
    return seedResizeFromH;
  }


  @JsonProperty(JSON_PROPERTY_SEED_RESIZE_FROM_H)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeedResizeFromH(Integer seedResizeFromH) {
    this.seedResizeFromH = seedResizeFromH;
  }


  public StableDiffusionProcessingTxt2Img seedResizeFromW(Integer seedResizeFromW) {
    
    this.seedResizeFromW = seedResizeFromW;
    return this;
  }

   /**
   * Get seedResizeFromW
   * @return seedResizeFromW
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEED_RESIZE_FROM_W)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSeedResizeFromW() {
    return seedResizeFromW;
  }


  @JsonProperty(JSON_PROPERTY_SEED_RESIZE_FROM_W)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeedResizeFromW(Integer seedResizeFromW) {
    this.seedResizeFromW = seedResizeFromW;
  }


  public StableDiffusionProcessingTxt2Img samplerName(String samplerName) {
    
    this.samplerName = samplerName;
    return this;
  }

   /**
   * Get samplerName
   * @return samplerName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SAMPLER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSamplerName() {
    return samplerName;
  }


  @JsonProperty(JSON_PROPERTY_SAMPLER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSamplerName(String samplerName) {
    this.samplerName = samplerName;
  }


  public StableDiffusionProcessingTxt2Img batchSize(Integer batchSize) {
    
    this.batchSize = batchSize;
    return this;
  }

   /**
   * Get batchSize
   * @return batchSize
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BATCH_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getBatchSize() {
    return batchSize;
  }


  @JsonProperty(JSON_PROPERTY_BATCH_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBatchSize(Integer batchSize) {
    this.batchSize = batchSize;
  }


  public StableDiffusionProcessingTxt2Img nIter(Integer nIter) {
    
    this.nIter = nIter;
    return this;
  }

   /**
   * Get nIter
   * @return nIter
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_N_ITER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getnIter() {
    return nIter;
  }


  @JsonProperty(JSON_PROPERTY_N_ITER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setnIter(Integer nIter) {
    this.nIter = nIter;
  }


  public StableDiffusionProcessingTxt2Img steps(Integer steps) {
    
    this.steps = steps;
    return this;
  }

   /**
   * Get steps
   * @return steps
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STEPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSteps() {
    return steps;
  }


  @JsonProperty(JSON_PROPERTY_STEPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSteps(Integer steps) {
    this.steps = steps;
  }


  public StableDiffusionProcessingTxt2Img cfgScale(BigDecimal cfgScale) {
    
    this.cfgScale = cfgScale;
    return this;
  }

   /**
   * Get cfgScale
   * @return cfgScale
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CFG_SCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getCfgScale() {
    return cfgScale;
  }


  @JsonProperty(JSON_PROPERTY_CFG_SCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCfgScale(BigDecimal cfgScale) {
    this.cfgScale = cfgScale;
  }


  public StableDiffusionProcessingTxt2Img width(Integer width) {
    
    this.width = width;
    return this;
  }

   /**
   * Get width
   * @return width
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWidth() {
    return width;
  }


  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWidth(Integer width) {
    this.width = width;
  }


  public StableDiffusionProcessingTxt2Img height(Integer height) {
    
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHeight() {
    return height;
  }


  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeight(Integer height) {
    this.height = height;
  }


  public StableDiffusionProcessingTxt2Img restoreFaces(Boolean restoreFaces) {
    
    this.restoreFaces = restoreFaces;
    return this;
  }

   /**
   * Get restoreFaces
   * @return restoreFaces
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESTORE_FACES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRestoreFaces() {
    return restoreFaces;
  }


  @JsonProperty(JSON_PROPERTY_RESTORE_FACES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRestoreFaces(Boolean restoreFaces) {
    this.restoreFaces = restoreFaces;
  }


  public StableDiffusionProcessingTxt2Img tiling(Boolean tiling) {
    
    this.tiling = tiling;
    return this;
  }

   /**
   * Get tiling
   * @return tiling
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TILING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTiling() {
    return tiling;
  }


  @JsonProperty(JSON_PROPERTY_TILING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTiling(Boolean tiling) {
    this.tiling = tiling;
  }


  public StableDiffusionProcessingTxt2Img doNotSaveSamples(Boolean doNotSaveSamples) {
    
    this.doNotSaveSamples = doNotSaveSamples;
    return this;
  }

   /**
   * Get doNotSaveSamples
   * @return doNotSaveSamples
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DO_NOT_SAVE_SAMPLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDoNotSaveSamples() {
    return doNotSaveSamples;
  }


  @JsonProperty(JSON_PROPERTY_DO_NOT_SAVE_SAMPLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDoNotSaveSamples(Boolean doNotSaveSamples) {
    this.doNotSaveSamples = doNotSaveSamples;
  }


  public StableDiffusionProcessingTxt2Img doNotSaveGrid(Boolean doNotSaveGrid) {
    
    this.doNotSaveGrid = doNotSaveGrid;
    return this;
  }

   /**
   * Get doNotSaveGrid
   * @return doNotSaveGrid
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DO_NOT_SAVE_GRID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDoNotSaveGrid() {
    return doNotSaveGrid;
  }


  @JsonProperty(JSON_PROPERTY_DO_NOT_SAVE_GRID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDoNotSaveGrid(Boolean doNotSaveGrid) {
    this.doNotSaveGrid = doNotSaveGrid;
  }


  public StableDiffusionProcessingTxt2Img eta(BigDecimal eta) {
    
    this.eta = eta;
    return this;
  }

   /**
   * Get eta
   * @return eta
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ETA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getEta() {
    return eta;
  }


  @JsonProperty(JSON_PROPERTY_ETA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEta(BigDecimal eta) {
    this.eta = eta;
  }


  public StableDiffusionProcessingTxt2Img denoisingStrength(BigDecimal denoisingStrength) {
    
    this.denoisingStrength = denoisingStrength;
    return this;
  }

   /**
   * Get denoisingStrength
   * @return denoisingStrength
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DENOISING_STRENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getDenoisingStrength() {
    return denoisingStrength;
  }


  @JsonProperty(JSON_PROPERTY_DENOISING_STRENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDenoisingStrength(BigDecimal denoisingStrength) {
    this.denoisingStrength = denoisingStrength;
  }


  public StableDiffusionProcessingTxt2Img sMinUncond(BigDecimal sMinUncond) {
    
    this.sMinUncond = sMinUncond;
    return this;
  }

   /**
   * Get sMinUncond
   * @return sMinUncond
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_S_MIN_UNCOND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getsMinUncond() {
    return sMinUncond;
  }


  @JsonProperty(JSON_PROPERTY_S_MIN_UNCOND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setsMinUncond(BigDecimal sMinUncond) {
    this.sMinUncond = sMinUncond;
  }


  public StableDiffusionProcessingTxt2Img sChurn(BigDecimal sChurn) {
    
    this.sChurn = sChurn;
    return this;
  }

   /**
   * Get sChurn
   * @return sChurn
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_S_CHURN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getsChurn() {
    return sChurn;
  }


  @JsonProperty(JSON_PROPERTY_S_CHURN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setsChurn(BigDecimal sChurn) {
    this.sChurn = sChurn;
  }


  public StableDiffusionProcessingTxt2Img sTmax(BigDecimal sTmax) {
    
    this.sTmax = sTmax;
    return this;
  }

   /**
   * Get sTmax
   * @return sTmax
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_S_TMAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getsTmax() {
    return sTmax;
  }


  @JsonProperty(JSON_PROPERTY_S_TMAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setsTmax(BigDecimal sTmax) {
    this.sTmax = sTmax;
  }


  public StableDiffusionProcessingTxt2Img sTmin(BigDecimal sTmin) {
    
    this.sTmin = sTmin;
    return this;
  }

   /**
   * Get sTmin
   * @return sTmin
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_S_TMIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getsTmin() {
    return sTmin;
  }


  @JsonProperty(JSON_PROPERTY_S_TMIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setsTmin(BigDecimal sTmin) {
    this.sTmin = sTmin;
  }


  public StableDiffusionProcessingTxt2Img sNoise(BigDecimal sNoise) {
    
    this.sNoise = sNoise;
    return this;
  }

   /**
   * Get sNoise
   * @return sNoise
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_S_NOISE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getsNoise() {
    return sNoise;
  }


  @JsonProperty(JSON_PROPERTY_S_NOISE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setsNoise(BigDecimal sNoise) {
    this.sNoise = sNoise;
  }


  public StableDiffusionProcessingTxt2Img overrideSettings(Object overrideSettings) {
    
    this.overrideSettings = overrideSettings;
    return this;
  }

   /**
   * Get overrideSettings
   * @return overrideSettings
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OVERRIDE_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getOverrideSettings() {
    return overrideSettings;
  }


  @JsonProperty(JSON_PROPERTY_OVERRIDE_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOverrideSettings(Object overrideSettings) {
    this.overrideSettings = overrideSettings;
  }


  public StableDiffusionProcessingTxt2Img overrideSettingsRestoreAfterwards(Boolean overrideSettingsRestoreAfterwards) {
    
    this.overrideSettingsRestoreAfterwards = overrideSettingsRestoreAfterwards;
    return this;
  }

   /**
   * Get overrideSettingsRestoreAfterwards
   * @return overrideSettingsRestoreAfterwards
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OVERRIDE_SETTINGS_RESTORE_AFTERWARDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOverrideSettingsRestoreAfterwards() {
    return overrideSettingsRestoreAfterwards;
  }


  @JsonProperty(JSON_PROPERTY_OVERRIDE_SETTINGS_RESTORE_AFTERWARDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOverrideSettingsRestoreAfterwards(Boolean overrideSettingsRestoreAfterwards) {
    this.overrideSettingsRestoreAfterwards = overrideSettingsRestoreAfterwards;
  }


  public StableDiffusionProcessingTxt2Img refinerCheckpoint(String refinerCheckpoint) {
    
    this.refinerCheckpoint = refinerCheckpoint;
    return this;
  }

   /**
   * Get refinerCheckpoint
   * @return refinerCheckpoint
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFINER_CHECKPOINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRefinerCheckpoint() {
    return refinerCheckpoint;
  }


  @JsonProperty(JSON_PROPERTY_REFINER_CHECKPOINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefinerCheckpoint(String refinerCheckpoint) {
    this.refinerCheckpoint = refinerCheckpoint;
  }


  public StableDiffusionProcessingTxt2Img refinerSwitchAt(BigDecimal refinerSwitchAt) {
    
    this.refinerSwitchAt = refinerSwitchAt;
    return this;
  }

   /**
   * Get refinerSwitchAt
   * @return refinerSwitchAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFINER_SWITCH_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getRefinerSwitchAt() {
    return refinerSwitchAt;
  }


  @JsonProperty(JSON_PROPERTY_REFINER_SWITCH_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefinerSwitchAt(BigDecimal refinerSwitchAt) {
    this.refinerSwitchAt = refinerSwitchAt;
  }


  public StableDiffusionProcessingTxt2Img disableExtraNetworks(Boolean disableExtraNetworks) {
    
    this.disableExtraNetworks = disableExtraNetworks;
    return this;
  }

   /**
   * Get disableExtraNetworks
   * @return disableExtraNetworks
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISABLE_EXTRA_NETWORKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisableExtraNetworks() {
    return disableExtraNetworks;
  }


  @JsonProperty(JSON_PROPERTY_DISABLE_EXTRA_NETWORKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisableExtraNetworks(Boolean disableExtraNetworks) {
    this.disableExtraNetworks = disableExtraNetworks;
  }


  public StableDiffusionProcessingTxt2Img comments(Object comments) {
    
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getComments() {
    return comments;
  }


  @JsonProperty(JSON_PROPERTY_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComments(Object comments) {
    this.comments = comments;
  }


  public StableDiffusionProcessingTxt2Img enableHr(Boolean enableHr) {
    
    this.enableHr = enableHr;
    return this;
  }

   /**
   * Get enableHr
   * @return enableHr
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENABLE_HR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnableHr() {
    return enableHr;
  }


  @JsonProperty(JSON_PROPERTY_ENABLE_HR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnableHr(Boolean enableHr) {
    this.enableHr = enableHr;
  }


  public StableDiffusionProcessingTxt2Img firstphaseWidth(Integer firstphaseWidth) {
    
    this.firstphaseWidth = firstphaseWidth;
    return this;
  }

   /**
   * Get firstphaseWidth
   * @return firstphaseWidth
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIRSTPHASE_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFirstphaseWidth() {
    return firstphaseWidth;
  }


  @JsonProperty(JSON_PROPERTY_FIRSTPHASE_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstphaseWidth(Integer firstphaseWidth) {
    this.firstphaseWidth = firstphaseWidth;
  }


  public StableDiffusionProcessingTxt2Img firstphaseHeight(Integer firstphaseHeight) {
    
    this.firstphaseHeight = firstphaseHeight;
    return this;
  }

   /**
   * Get firstphaseHeight
   * @return firstphaseHeight
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIRSTPHASE_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFirstphaseHeight() {
    return firstphaseHeight;
  }


  @JsonProperty(JSON_PROPERTY_FIRSTPHASE_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstphaseHeight(Integer firstphaseHeight) {
    this.firstphaseHeight = firstphaseHeight;
  }


  public StableDiffusionProcessingTxt2Img hrScale(BigDecimal hrScale) {
    
    this.hrScale = hrScale;
    return this;
  }

   /**
   * Get hrScale
   * @return hrScale
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HR_SCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getHrScale() {
    return hrScale;
  }


  @JsonProperty(JSON_PROPERTY_HR_SCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHrScale(BigDecimal hrScale) {
    this.hrScale = hrScale;
  }


  public StableDiffusionProcessingTxt2Img hrUpscaler(String hrUpscaler) {
    
    this.hrUpscaler = hrUpscaler;
    return this;
  }

   /**
   * Get hrUpscaler
   * @return hrUpscaler
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HR_UPSCALER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHrUpscaler() {
    return hrUpscaler;
  }


  @JsonProperty(JSON_PROPERTY_HR_UPSCALER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHrUpscaler(String hrUpscaler) {
    this.hrUpscaler = hrUpscaler;
  }


  public StableDiffusionProcessingTxt2Img hrSecondPassSteps(Integer hrSecondPassSteps) {
    
    this.hrSecondPassSteps = hrSecondPassSteps;
    return this;
  }

   /**
   * Get hrSecondPassSteps
   * @return hrSecondPassSteps
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HR_SECOND_PASS_STEPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHrSecondPassSteps() {
    return hrSecondPassSteps;
  }


  @JsonProperty(JSON_PROPERTY_HR_SECOND_PASS_STEPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHrSecondPassSteps(Integer hrSecondPassSteps) {
    this.hrSecondPassSteps = hrSecondPassSteps;
  }


  public StableDiffusionProcessingTxt2Img hrResizeX(Integer hrResizeX) {
    
    this.hrResizeX = hrResizeX;
    return this;
  }

   /**
   * Get hrResizeX
   * @return hrResizeX
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HR_RESIZE_X)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHrResizeX() {
    return hrResizeX;
  }


  @JsonProperty(JSON_PROPERTY_HR_RESIZE_X)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHrResizeX(Integer hrResizeX) {
    this.hrResizeX = hrResizeX;
  }


  public StableDiffusionProcessingTxt2Img hrResizeY(Integer hrResizeY) {
    
    this.hrResizeY = hrResizeY;
    return this;
  }

   /**
   * Get hrResizeY
   * @return hrResizeY
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HR_RESIZE_Y)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHrResizeY() {
    return hrResizeY;
  }


  @JsonProperty(JSON_PROPERTY_HR_RESIZE_Y)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHrResizeY(Integer hrResizeY) {
    this.hrResizeY = hrResizeY;
  }


  public StableDiffusionProcessingTxt2Img hrCheckpointName(String hrCheckpointName) {
    
    this.hrCheckpointName = hrCheckpointName;
    return this;
  }

   /**
   * Get hrCheckpointName
   * @return hrCheckpointName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HR_CHECKPOINT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHrCheckpointName() {
    return hrCheckpointName;
  }


  @JsonProperty(JSON_PROPERTY_HR_CHECKPOINT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHrCheckpointName(String hrCheckpointName) {
    this.hrCheckpointName = hrCheckpointName;
  }


  public StableDiffusionProcessingTxt2Img hrSamplerName(String hrSamplerName) {
    
    this.hrSamplerName = hrSamplerName;
    return this;
  }

   /**
   * Get hrSamplerName
   * @return hrSamplerName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HR_SAMPLER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHrSamplerName() {
    return hrSamplerName;
  }


  @JsonProperty(JSON_PROPERTY_HR_SAMPLER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHrSamplerName(String hrSamplerName) {
    this.hrSamplerName = hrSamplerName;
  }


  public StableDiffusionProcessingTxt2Img hrPrompt(String hrPrompt) {
    
    this.hrPrompt = hrPrompt;
    return this;
  }

   /**
   * Get hrPrompt
   * @return hrPrompt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HR_PROMPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHrPrompt() {
    return hrPrompt;
  }


  @JsonProperty(JSON_PROPERTY_HR_PROMPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHrPrompt(String hrPrompt) {
    this.hrPrompt = hrPrompt;
  }


  public StableDiffusionProcessingTxt2Img hrNegativePrompt(String hrNegativePrompt) {
    
    this.hrNegativePrompt = hrNegativePrompt;
    return this;
  }

   /**
   * Get hrNegativePrompt
   * @return hrNegativePrompt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HR_NEGATIVE_PROMPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHrNegativePrompt() {
    return hrNegativePrompt;
  }


  @JsonProperty(JSON_PROPERTY_HR_NEGATIVE_PROMPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHrNegativePrompt(String hrNegativePrompt) {
    this.hrNegativePrompt = hrNegativePrompt;
  }


  public StableDiffusionProcessingTxt2Img samplerIndex(String samplerIndex) {
    
    this.samplerIndex = samplerIndex;
    return this;
  }

   /**
   * Get samplerIndex
   * @return samplerIndex
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SAMPLER_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSamplerIndex() {
    return samplerIndex;
  }


  @JsonProperty(JSON_PROPERTY_SAMPLER_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSamplerIndex(String samplerIndex) {
    this.samplerIndex = samplerIndex;
  }


  public StableDiffusionProcessingTxt2Img scriptName(String scriptName) {
    
    this.scriptName = scriptName;
    return this;
  }

   /**
   * Get scriptName
   * @return scriptName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCRIPT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getScriptName() {
    return scriptName;
  }


  @JsonProperty(JSON_PROPERTY_SCRIPT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScriptName(String scriptName) {
    this.scriptName = scriptName;
  }


  public StableDiffusionProcessingTxt2Img scriptArgs(List<Object> scriptArgs) {
    
    this.scriptArgs = scriptArgs;
    return this;
  }

  public StableDiffusionProcessingTxt2Img addScriptArgsItem(Object scriptArgsItem) {
    if (this.scriptArgs == null) {
      this.scriptArgs = new ArrayList<>();
    }
    this.scriptArgs.add(scriptArgsItem);
    return this;
  }

   /**
   * Get scriptArgs
   * @return scriptArgs
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCRIPT_ARGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getScriptArgs() {
    return scriptArgs;
  }


  @JsonProperty(JSON_PROPERTY_SCRIPT_ARGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScriptArgs(List<Object> scriptArgs) {
    this.scriptArgs = scriptArgs;
  }


  public StableDiffusionProcessingTxt2Img sendImages(Boolean sendImages) {
    
    this.sendImages = sendImages;
    return this;
  }

   /**
   * Get sendImages
   * @return sendImages
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEND_IMAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSendImages() {
    return sendImages;
  }


  @JsonProperty(JSON_PROPERTY_SEND_IMAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSendImages(Boolean sendImages) {
    this.sendImages = sendImages;
  }


  public StableDiffusionProcessingTxt2Img saveImages(Boolean saveImages) {
    
    this.saveImages = saveImages;
    return this;
  }

   /**
   * Get saveImages
   * @return saveImages
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SAVE_IMAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSaveImages() {
    return saveImages;
  }


  @JsonProperty(JSON_PROPERTY_SAVE_IMAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSaveImages(Boolean saveImages) {
    this.saveImages = saveImages;
  }


  public StableDiffusionProcessingTxt2Img alwaysonScripts(Object alwaysonScripts) {
    
    this.alwaysonScripts = alwaysonScripts;
    return this;
  }

   /**
   * Get alwaysonScripts
   * @return alwaysonScripts
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALWAYSON_SCRIPTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getAlwaysonScripts() {
    return alwaysonScripts;
  }


  @JsonProperty(JSON_PROPERTY_ALWAYSON_SCRIPTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlwaysonScripts(Object alwaysonScripts) {
    this.alwaysonScripts = alwaysonScripts;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StableDiffusionProcessingTxt2Img stableDiffusionProcessingTxt2Img = (StableDiffusionProcessingTxt2Img) o;
    return Objects.equals(this.prompt, stableDiffusionProcessingTxt2Img.prompt) &&
        Objects.equals(this.negativePrompt, stableDiffusionProcessingTxt2Img.negativePrompt) &&
        Objects.equals(this.styles, stableDiffusionProcessingTxt2Img.styles) &&
        Objects.equals(this.seed, stableDiffusionProcessingTxt2Img.seed) &&
        Objects.equals(this.subseed, stableDiffusionProcessingTxt2Img.subseed) &&
        Objects.equals(this.subseedStrength, stableDiffusionProcessingTxt2Img.subseedStrength) &&
        Objects.equals(this.seedResizeFromH, stableDiffusionProcessingTxt2Img.seedResizeFromH) &&
        Objects.equals(this.seedResizeFromW, stableDiffusionProcessingTxt2Img.seedResizeFromW) &&
        Objects.equals(this.samplerName, stableDiffusionProcessingTxt2Img.samplerName) &&
        Objects.equals(this.batchSize, stableDiffusionProcessingTxt2Img.batchSize) &&
        Objects.equals(this.nIter, stableDiffusionProcessingTxt2Img.nIter) &&
        Objects.equals(this.steps, stableDiffusionProcessingTxt2Img.steps) &&
        Objects.equals(this.cfgScale, stableDiffusionProcessingTxt2Img.cfgScale) &&
        Objects.equals(this.width, stableDiffusionProcessingTxt2Img.width) &&
        Objects.equals(this.height, stableDiffusionProcessingTxt2Img.height) &&
        Objects.equals(this.restoreFaces, stableDiffusionProcessingTxt2Img.restoreFaces) &&
        Objects.equals(this.tiling, stableDiffusionProcessingTxt2Img.tiling) &&
        Objects.equals(this.doNotSaveSamples, stableDiffusionProcessingTxt2Img.doNotSaveSamples) &&
        Objects.equals(this.doNotSaveGrid, stableDiffusionProcessingTxt2Img.doNotSaveGrid) &&
        Objects.equals(this.eta, stableDiffusionProcessingTxt2Img.eta) &&
        Objects.equals(this.denoisingStrength, stableDiffusionProcessingTxt2Img.denoisingStrength) &&
        Objects.equals(this.sMinUncond, stableDiffusionProcessingTxt2Img.sMinUncond) &&
        Objects.equals(this.sChurn, stableDiffusionProcessingTxt2Img.sChurn) &&
        Objects.equals(this.sTmax, stableDiffusionProcessingTxt2Img.sTmax) &&
        Objects.equals(this.sTmin, stableDiffusionProcessingTxt2Img.sTmin) &&
        Objects.equals(this.sNoise, stableDiffusionProcessingTxt2Img.sNoise) &&
        Objects.equals(this.overrideSettings, stableDiffusionProcessingTxt2Img.overrideSettings) &&
        Objects.equals(this.overrideSettingsRestoreAfterwards, stableDiffusionProcessingTxt2Img.overrideSettingsRestoreAfterwards) &&
        Objects.equals(this.refinerCheckpoint, stableDiffusionProcessingTxt2Img.refinerCheckpoint) &&
        Objects.equals(this.refinerSwitchAt, stableDiffusionProcessingTxt2Img.refinerSwitchAt) &&
        Objects.equals(this.disableExtraNetworks, stableDiffusionProcessingTxt2Img.disableExtraNetworks) &&
        Objects.equals(this.comments, stableDiffusionProcessingTxt2Img.comments) &&
        Objects.equals(this.enableHr, stableDiffusionProcessingTxt2Img.enableHr) &&
        Objects.equals(this.firstphaseWidth, stableDiffusionProcessingTxt2Img.firstphaseWidth) &&
        Objects.equals(this.firstphaseHeight, stableDiffusionProcessingTxt2Img.firstphaseHeight) &&
        Objects.equals(this.hrScale, stableDiffusionProcessingTxt2Img.hrScale) &&
        Objects.equals(this.hrUpscaler, stableDiffusionProcessingTxt2Img.hrUpscaler) &&
        Objects.equals(this.hrSecondPassSteps, stableDiffusionProcessingTxt2Img.hrSecondPassSteps) &&
        Objects.equals(this.hrResizeX, stableDiffusionProcessingTxt2Img.hrResizeX) &&
        Objects.equals(this.hrResizeY, stableDiffusionProcessingTxt2Img.hrResizeY) &&
        Objects.equals(this.hrCheckpointName, stableDiffusionProcessingTxt2Img.hrCheckpointName) &&
        Objects.equals(this.hrSamplerName, stableDiffusionProcessingTxt2Img.hrSamplerName) &&
        Objects.equals(this.hrPrompt, stableDiffusionProcessingTxt2Img.hrPrompt) &&
        Objects.equals(this.hrNegativePrompt, stableDiffusionProcessingTxt2Img.hrNegativePrompt) &&
        Objects.equals(this.samplerIndex, stableDiffusionProcessingTxt2Img.samplerIndex) &&
        Objects.equals(this.scriptName, stableDiffusionProcessingTxt2Img.scriptName) &&
        Objects.equals(this.scriptArgs, stableDiffusionProcessingTxt2Img.scriptArgs) &&
        Objects.equals(this.sendImages, stableDiffusionProcessingTxt2Img.sendImages) &&
        Objects.equals(this.saveImages, stableDiffusionProcessingTxt2Img.saveImages) &&
        Objects.equals(this.alwaysonScripts, stableDiffusionProcessingTxt2Img.alwaysonScripts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prompt, negativePrompt, styles, seed, subseed, subseedStrength, seedResizeFromH, seedResizeFromW, samplerName, batchSize, nIter, steps, cfgScale, width, height, restoreFaces, tiling, doNotSaveSamples, doNotSaveGrid, eta, denoisingStrength, sMinUncond, sChurn, sTmax, sTmin, sNoise, overrideSettings, overrideSettingsRestoreAfterwards, refinerCheckpoint, refinerSwitchAt, disableExtraNetworks, comments, enableHr, firstphaseWidth, firstphaseHeight, hrScale, hrUpscaler, hrSecondPassSteps, hrResizeX, hrResizeY, hrCheckpointName, hrSamplerName, hrPrompt, hrNegativePrompt, samplerIndex, scriptName, scriptArgs, sendImages, saveImages, alwaysonScripts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StableDiffusionProcessingTxt2Img {\n");
    sb.append("    prompt: ").append(toIndentedString(prompt)).append("\n");
    sb.append("    negativePrompt: ").append(toIndentedString(negativePrompt)).append("\n");
    sb.append("    styles: ").append(toIndentedString(styles)).append("\n");
    sb.append("    seed: ").append(toIndentedString(seed)).append("\n");
    sb.append("    subseed: ").append(toIndentedString(subseed)).append("\n");
    sb.append("    subseedStrength: ").append(toIndentedString(subseedStrength)).append("\n");
    sb.append("    seedResizeFromH: ").append(toIndentedString(seedResizeFromH)).append("\n");
    sb.append("    seedResizeFromW: ").append(toIndentedString(seedResizeFromW)).append("\n");
    sb.append("    samplerName: ").append(toIndentedString(samplerName)).append("\n");
    sb.append("    batchSize: ").append(toIndentedString(batchSize)).append("\n");
    sb.append("    nIter: ").append(toIndentedString(nIter)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("    cfgScale: ").append(toIndentedString(cfgScale)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    restoreFaces: ").append(toIndentedString(restoreFaces)).append("\n");
    sb.append("    tiling: ").append(toIndentedString(tiling)).append("\n");
    sb.append("    doNotSaveSamples: ").append(toIndentedString(doNotSaveSamples)).append("\n");
    sb.append("    doNotSaveGrid: ").append(toIndentedString(doNotSaveGrid)).append("\n");
    sb.append("    eta: ").append(toIndentedString(eta)).append("\n");
    sb.append("    denoisingStrength: ").append(toIndentedString(denoisingStrength)).append("\n");
    sb.append("    sMinUncond: ").append(toIndentedString(sMinUncond)).append("\n");
    sb.append("    sChurn: ").append(toIndentedString(sChurn)).append("\n");
    sb.append("    sTmax: ").append(toIndentedString(sTmax)).append("\n");
    sb.append("    sTmin: ").append(toIndentedString(sTmin)).append("\n");
    sb.append("    sNoise: ").append(toIndentedString(sNoise)).append("\n");
    sb.append("    overrideSettings: ").append(toIndentedString(overrideSettings)).append("\n");
    sb.append("    overrideSettingsRestoreAfterwards: ").append(toIndentedString(overrideSettingsRestoreAfterwards)).append("\n");
    sb.append("    refinerCheckpoint: ").append(toIndentedString(refinerCheckpoint)).append("\n");
    sb.append("    refinerSwitchAt: ").append(toIndentedString(refinerSwitchAt)).append("\n");
    sb.append("    disableExtraNetworks: ").append(toIndentedString(disableExtraNetworks)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    enableHr: ").append(toIndentedString(enableHr)).append("\n");
    sb.append("    firstphaseWidth: ").append(toIndentedString(firstphaseWidth)).append("\n");
    sb.append("    firstphaseHeight: ").append(toIndentedString(firstphaseHeight)).append("\n");
    sb.append("    hrScale: ").append(toIndentedString(hrScale)).append("\n");
    sb.append("    hrUpscaler: ").append(toIndentedString(hrUpscaler)).append("\n");
    sb.append("    hrSecondPassSteps: ").append(toIndentedString(hrSecondPassSteps)).append("\n");
    sb.append("    hrResizeX: ").append(toIndentedString(hrResizeX)).append("\n");
    sb.append("    hrResizeY: ").append(toIndentedString(hrResizeY)).append("\n");
    sb.append("    hrCheckpointName: ").append(toIndentedString(hrCheckpointName)).append("\n");
    sb.append("    hrSamplerName: ").append(toIndentedString(hrSamplerName)).append("\n");
    sb.append("    hrPrompt: ").append(toIndentedString(hrPrompt)).append("\n");
    sb.append("    hrNegativePrompt: ").append(toIndentedString(hrNegativePrompt)).append("\n");
    sb.append("    samplerIndex: ").append(toIndentedString(samplerIndex)).append("\n");
    sb.append("    scriptName: ").append(toIndentedString(scriptName)).append("\n");
    sb.append("    scriptArgs: ").append(toIndentedString(scriptArgs)).append("\n");
    sb.append("    sendImages: ").append(toIndentedString(sendImages)).append("\n");
    sb.append("    saveImages: ").append(toIndentedString(saveImages)).append("\n");
    sb.append("    alwaysonScripts: ").append(toIndentedString(alwaysonScripts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

