/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.automatic.webui.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * StableDiffusionProcessingImg2Img
 */
@JsonPropertyOrder({
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_PROMPT,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_NEGATIVE_PROMPT,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_STYLES,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_SEED,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_SUBSEED,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_SUBSEED_STRENGTH,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_SEED_RESIZE_FROM_H,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_SEED_RESIZE_FROM_W,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_SAMPLER_NAME,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_BATCH_SIZE,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_N_ITER,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_STEPS,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_CFG_SCALE,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_WIDTH,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_HEIGHT,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_RESTORE_FACES,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_TILING,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_DO_NOT_SAVE_SAMPLES,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_DO_NOT_SAVE_GRID,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_ETA,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_DENOISING_STRENGTH,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_S_MIN_UNCOND,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_S_CHURN,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_S_TMAX,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_S_TMIN,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_S_NOISE,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_OVERRIDE_SETTINGS,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_OVERRIDE_SETTINGS_RESTORE_AFTERWARDS,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_REFINER_CHECKPOINT,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_REFINER_SWITCH_AT,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_DISABLE_EXTRA_NETWORKS,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_COMMENTS,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_INIT_IMAGES,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_RESIZE_MODE,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_IMAGE_CFG_SCALE,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_MASK,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_MASK_BLUR_X,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_MASK_BLUR_Y,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_MASK_BLUR,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_INPAINTING_FILL,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_INPAINT_FULL_RES,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_INPAINT_FULL_RES_PADDING,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_INPAINTING_MASK_INVERT,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_INITIAL_NOISE_MULTIPLIER,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_LATENT_MASK,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_SAMPLER_INDEX,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_INCLUDE_INIT_IMAGES,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_SCRIPT_NAME,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_SCRIPT_ARGS,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_SEND_IMAGES,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_SAVE_IMAGES,
  StableDiffusionProcessingImg2Img.JSON_PROPERTY_ALWAYSON_SCRIPTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-27T01:31:55.639766089+03:00[Europe/Moscow]")
public class StableDiffusionProcessingImg2Img {
  public static final String JSON_PROPERTY_PROMPT = "prompt";
  private String prompt = "";

  public static final String JSON_PROPERTY_NEGATIVE_PROMPT = "negative_prompt";
  private String negativePrompt = "";

  public static final String JSON_PROPERTY_STYLES = "styles";
  private List<String> styles;

  public static final String JSON_PROPERTY_SEED = "seed";
  private Integer seed = -1;

  public static final String JSON_PROPERTY_SUBSEED = "subseed";
  private Integer subseed = -1;

  public static final String JSON_PROPERTY_SUBSEED_STRENGTH = "subseed_strength";
  private BigDecimal subseedStrength = new BigDecimal("0");

  public static final String JSON_PROPERTY_SEED_RESIZE_FROM_H = "seed_resize_from_h";
  private Integer seedResizeFromH = -1;

  public static final String JSON_PROPERTY_SEED_RESIZE_FROM_W = "seed_resize_from_w";
  private Integer seedResizeFromW = -1;

  public static final String JSON_PROPERTY_SAMPLER_NAME = "sampler_name";
  private String samplerName;

  public static final String JSON_PROPERTY_BATCH_SIZE = "batch_size";
  private Integer batchSize = 1;

  public static final String JSON_PROPERTY_N_ITER = "n_iter";
  private Integer nIter = 1;

  public static final String JSON_PROPERTY_STEPS = "steps";
  private Integer steps = 50;

  public static final String JSON_PROPERTY_CFG_SCALE = "cfg_scale";
  private BigDecimal cfgScale = new BigDecimal("7.0");

  public static final String JSON_PROPERTY_WIDTH = "width";
  private Integer width = 512;

  public static final String JSON_PROPERTY_HEIGHT = "height";
  private Integer height = 512;

  public static final String JSON_PROPERTY_RESTORE_FACES = "restore_faces";
  private Boolean restoreFaces;

  public static final String JSON_PROPERTY_TILING = "tiling";
  private Boolean tiling;

  public static final String JSON_PROPERTY_DO_NOT_SAVE_SAMPLES = "do_not_save_samples";
  private Boolean doNotSaveSamples = false;

  public static final String JSON_PROPERTY_DO_NOT_SAVE_GRID = "do_not_save_grid";
  private Boolean doNotSaveGrid = false;

  public static final String JSON_PROPERTY_ETA = "eta";
  private BigDecimal eta;

  public static final String JSON_PROPERTY_DENOISING_STRENGTH = "denoising_strength";
  private BigDecimal denoisingStrength = new BigDecimal("0.75");

  public static final String JSON_PROPERTY_S_MIN_UNCOND = "s_min_uncond";
  private BigDecimal sMinUncond;

  public static final String JSON_PROPERTY_S_CHURN = "s_churn";
  private BigDecimal sChurn;

  public static final String JSON_PROPERTY_S_TMAX = "s_tmax";
  private BigDecimal sTmax;

  public static final String JSON_PROPERTY_S_TMIN = "s_tmin";
  private BigDecimal sTmin;

  public static final String JSON_PROPERTY_S_NOISE = "s_noise";
  private BigDecimal sNoise;

  public static final String JSON_PROPERTY_OVERRIDE_SETTINGS = "override_settings";
  private Object overrideSettings;

  public static final String JSON_PROPERTY_OVERRIDE_SETTINGS_RESTORE_AFTERWARDS = "override_settings_restore_afterwards";
  private Boolean overrideSettingsRestoreAfterwards = true;

  public static final String JSON_PROPERTY_REFINER_CHECKPOINT = "refiner_checkpoint";
  private String refinerCheckpoint;

  public static final String JSON_PROPERTY_REFINER_SWITCH_AT = "refiner_switch_at";
  private BigDecimal refinerSwitchAt;

  public static final String JSON_PROPERTY_DISABLE_EXTRA_NETWORKS = "disable_extra_networks";
  private Boolean disableExtraNetworks = false;

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  private Object comments;

  public static final String JSON_PROPERTY_INIT_IMAGES = "init_images";
  private List<Object> initImages;

  public static final String JSON_PROPERTY_RESIZE_MODE = "resize_mode";
  private Integer resizeMode = 0;

  public static final String JSON_PROPERTY_IMAGE_CFG_SCALE = "image_cfg_scale";
  private BigDecimal imageCfgScale;

  public static final String JSON_PROPERTY_MASK = "mask";
  private String mask;

  public static final String JSON_PROPERTY_MASK_BLUR_X = "mask_blur_x";
  private Integer maskBlurX = 4;

  public static final String JSON_PROPERTY_MASK_BLUR_Y = "mask_blur_y";
  private Integer maskBlurY = 4;

  public static final String JSON_PROPERTY_MASK_BLUR = "mask_blur";
  private Integer maskBlur;

  public static final String JSON_PROPERTY_INPAINTING_FILL = "inpainting_fill";
  private Integer inpaintingFill = 0;

  public static final String JSON_PROPERTY_INPAINT_FULL_RES = "inpaint_full_res";
  private Boolean inpaintFullRes = true;

  public static final String JSON_PROPERTY_INPAINT_FULL_RES_PADDING = "inpaint_full_res_padding";
  private Integer inpaintFullResPadding = 0;

  public static final String JSON_PROPERTY_INPAINTING_MASK_INVERT = "inpainting_mask_invert";
  private Integer inpaintingMaskInvert = 0;

  public static final String JSON_PROPERTY_INITIAL_NOISE_MULTIPLIER = "initial_noise_multiplier";
  private BigDecimal initialNoiseMultiplier;

  public static final String JSON_PROPERTY_LATENT_MASK = "latent_mask";
  private String latentMask;

  public static final String JSON_PROPERTY_SAMPLER_INDEX = "sampler_index";
  private String samplerIndex = "Euler";

  public static final String JSON_PROPERTY_INCLUDE_INIT_IMAGES = "include_init_images";
  private Boolean includeInitImages = false;

  public static final String JSON_PROPERTY_SCRIPT_NAME = "script_name";
  private String scriptName;

  public static final String JSON_PROPERTY_SCRIPT_ARGS = "script_args";
  private List<Object> scriptArgs = new ArrayList<>();

  public static final String JSON_PROPERTY_SEND_IMAGES = "send_images";
  private Boolean sendImages = true;

  public static final String JSON_PROPERTY_SAVE_IMAGES = "save_images";
  private Boolean saveImages = false;

  public static final String JSON_PROPERTY_ALWAYSON_SCRIPTS = "alwayson_scripts";
  private Object alwaysonScripts = {};

  public StableDiffusionProcessingImg2Img() {
  }

  public StableDiffusionProcessingImg2Img prompt(String prompt) {
    
    this.prompt = prompt;
    return this;
  }

   /**
   * Get prompt
   * @return prompt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROMPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPrompt() {
    return prompt;
  }


  @JsonProperty(JSON_PROPERTY_PROMPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrompt(String prompt) {
    this.prompt = prompt;
  }


  public StableDiffusionProcessingImg2Img negativePrompt(String negativePrompt) {
    
    this.negativePrompt = negativePrompt;
    return this;
  }

   /**
   * Get negativePrompt
   * @return negativePrompt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEGATIVE_PROMPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNegativePrompt() {
    return negativePrompt;
  }


  @JsonProperty(JSON_PROPERTY_NEGATIVE_PROMPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNegativePrompt(String negativePrompt) {
    this.negativePrompt = negativePrompt;
  }


  public StableDiffusionProcessingImg2Img styles(List<String> styles) {
    
    this.styles = styles;
    return this;
  }

  public StableDiffusionProcessingImg2Img addStylesItem(String stylesItem) {
    if (this.styles == null) {
      this.styles = new ArrayList<>();
    }
    this.styles.add(stylesItem);
    return this;
  }

   /**
   * Get styles
   * @return styles
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STYLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getStyles() {
    return styles;
  }


  @JsonProperty(JSON_PROPERTY_STYLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStyles(List<String> styles) {
    this.styles = styles;
  }


  public StableDiffusionProcessingImg2Img seed(Integer seed) {
    
    this.seed = seed;
    return this;
  }

   /**
   * Get seed
   * @return seed
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSeed() {
    return seed;
  }


  @JsonProperty(JSON_PROPERTY_SEED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeed(Integer seed) {
    this.seed = seed;
  }


  public StableDiffusionProcessingImg2Img subseed(Integer subseed) {
    
    this.subseed = subseed;
    return this;
  }

   /**
   * Get subseed
   * @return subseed
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUBSEED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSubseed() {
    return subseed;
  }


  @JsonProperty(JSON_PROPERTY_SUBSEED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubseed(Integer subseed) {
    this.subseed = subseed;
  }


  public StableDiffusionProcessingImg2Img subseedStrength(BigDecimal subseedStrength) {
    
    this.subseedStrength = subseedStrength;
    return this;
  }

   /**
   * Get subseedStrength
   * @return subseedStrength
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUBSEED_STRENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getSubseedStrength() {
    return subseedStrength;
  }


  @JsonProperty(JSON_PROPERTY_SUBSEED_STRENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubseedStrength(BigDecimal subseedStrength) {
    this.subseedStrength = subseedStrength;
  }


  public StableDiffusionProcessingImg2Img seedResizeFromH(Integer seedResizeFromH) {
    
    this.seedResizeFromH = seedResizeFromH;
    return this;
  }

   /**
   * Get seedResizeFromH
   * @return seedResizeFromH
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEED_RESIZE_FROM_H)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSeedResizeFromH() {
    return seedResizeFromH;
  }


  @JsonProperty(JSON_PROPERTY_SEED_RESIZE_FROM_H)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeedResizeFromH(Integer seedResizeFromH) {
    this.seedResizeFromH = seedResizeFromH;
  }


  public StableDiffusionProcessingImg2Img seedResizeFromW(Integer seedResizeFromW) {
    
    this.seedResizeFromW = seedResizeFromW;
    return this;
  }

   /**
   * Get seedResizeFromW
   * @return seedResizeFromW
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEED_RESIZE_FROM_W)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSeedResizeFromW() {
    return seedResizeFromW;
  }


  @JsonProperty(JSON_PROPERTY_SEED_RESIZE_FROM_W)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeedResizeFromW(Integer seedResizeFromW) {
    this.seedResizeFromW = seedResizeFromW;
  }


  public StableDiffusionProcessingImg2Img samplerName(String samplerName) {
    
    this.samplerName = samplerName;
    return this;
  }

   /**
   * Get samplerName
   * @return samplerName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SAMPLER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSamplerName() {
    return samplerName;
  }


  @JsonProperty(JSON_PROPERTY_SAMPLER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSamplerName(String samplerName) {
    this.samplerName = samplerName;
  }


  public StableDiffusionProcessingImg2Img batchSize(Integer batchSize) {
    
    this.batchSize = batchSize;
    return this;
  }

   /**
   * Get batchSize
   * @return batchSize
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BATCH_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getBatchSize() {
    return batchSize;
  }


  @JsonProperty(JSON_PROPERTY_BATCH_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBatchSize(Integer batchSize) {
    this.batchSize = batchSize;
  }


  public StableDiffusionProcessingImg2Img nIter(Integer nIter) {
    
    this.nIter = nIter;
    return this;
  }

   /**
   * Get nIter
   * @return nIter
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_N_ITER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getnIter() {
    return nIter;
  }


  @JsonProperty(JSON_PROPERTY_N_ITER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setnIter(Integer nIter) {
    this.nIter = nIter;
  }


  public StableDiffusionProcessingImg2Img steps(Integer steps) {
    
    this.steps = steps;
    return this;
  }

   /**
   * Get steps
   * @return steps
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STEPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSteps() {
    return steps;
  }


  @JsonProperty(JSON_PROPERTY_STEPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSteps(Integer steps) {
    this.steps = steps;
  }


  public StableDiffusionProcessingImg2Img cfgScale(BigDecimal cfgScale) {
    
    this.cfgScale = cfgScale;
    return this;
  }

   /**
   * Get cfgScale
   * @return cfgScale
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CFG_SCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getCfgScale() {
    return cfgScale;
  }


  @JsonProperty(JSON_PROPERTY_CFG_SCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCfgScale(BigDecimal cfgScale) {
    this.cfgScale = cfgScale;
  }


  public StableDiffusionProcessingImg2Img width(Integer width) {
    
    this.width = width;
    return this;
  }

   /**
   * Get width
   * @return width
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWidth() {
    return width;
  }


  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWidth(Integer width) {
    this.width = width;
  }


  public StableDiffusionProcessingImg2Img height(Integer height) {
    
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHeight() {
    return height;
  }


  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeight(Integer height) {
    this.height = height;
  }


  public StableDiffusionProcessingImg2Img restoreFaces(Boolean restoreFaces) {
    
    this.restoreFaces = restoreFaces;
    return this;
  }

   /**
   * Get restoreFaces
   * @return restoreFaces
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESTORE_FACES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRestoreFaces() {
    return restoreFaces;
  }


  @JsonProperty(JSON_PROPERTY_RESTORE_FACES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRestoreFaces(Boolean restoreFaces) {
    this.restoreFaces = restoreFaces;
  }


  public StableDiffusionProcessingImg2Img tiling(Boolean tiling) {
    
    this.tiling = tiling;
    return this;
  }

   /**
   * Get tiling
   * @return tiling
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TILING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTiling() {
    return tiling;
  }


  @JsonProperty(JSON_PROPERTY_TILING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTiling(Boolean tiling) {
    this.tiling = tiling;
  }


  public StableDiffusionProcessingImg2Img doNotSaveSamples(Boolean doNotSaveSamples) {
    
    this.doNotSaveSamples = doNotSaveSamples;
    return this;
  }

   /**
   * Get doNotSaveSamples
   * @return doNotSaveSamples
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DO_NOT_SAVE_SAMPLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDoNotSaveSamples() {
    return doNotSaveSamples;
  }


  @JsonProperty(JSON_PROPERTY_DO_NOT_SAVE_SAMPLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDoNotSaveSamples(Boolean doNotSaveSamples) {
    this.doNotSaveSamples = doNotSaveSamples;
  }


  public StableDiffusionProcessingImg2Img doNotSaveGrid(Boolean doNotSaveGrid) {
    
    this.doNotSaveGrid = doNotSaveGrid;
    return this;
  }

   /**
   * Get doNotSaveGrid
   * @return doNotSaveGrid
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DO_NOT_SAVE_GRID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDoNotSaveGrid() {
    return doNotSaveGrid;
  }


  @JsonProperty(JSON_PROPERTY_DO_NOT_SAVE_GRID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDoNotSaveGrid(Boolean doNotSaveGrid) {
    this.doNotSaveGrid = doNotSaveGrid;
  }


  public StableDiffusionProcessingImg2Img eta(BigDecimal eta) {
    
    this.eta = eta;
    return this;
  }

   /**
   * Get eta
   * @return eta
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ETA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getEta() {
    return eta;
  }


  @JsonProperty(JSON_PROPERTY_ETA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEta(BigDecimal eta) {
    this.eta = eta;
  }


  public StableDiffusionProcessingImg2Img denoisingStrength(BigDecimal denoisingStrength) {
    
    this.denoisingStrength = denoisingStrength;
    return this;
  }

   /**
   * Get denoisingStrength
   * @return denoisingStrength
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DENOISING_STRENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getDenoisingStrength() {
    return denoisingStrength;
  }


  @JsonProperty(JSON_PROPERTY_DENOISING_STRENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDenoisingStrength(BigDecimal denoisingStrength) {
    this.denoisingStrength = denoisingStrength;
  }


  public StableDiffusionProcessingImg2Img sMinUncond(BigDecimal sMinUncond) {
    
    this.sMinUncond = sMinUncond;
    return this;
  }

   /**
   * Get sMinUncond
   * @return sMinUncond
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_S_MIN_UNCOND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getsMinUncond() {
    return sMinUncond;
  }


  @JsonProperty(JSON_PROPERTY_S_MIN_UNCOND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setsMinUncond(BigDecimal sMinUncond) {
    this.sMinUncond = sMinUncond;
  }


  public StableDiffusionProcessingImg2Img sChurn(BigDecimal sChurn) {
    
    this.sChurn = sChurn;
    return this;
  }

   /**
   * Get sChurn
   * @return sChurn
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_S_CHURN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getsChurn() {
    return sChurn;
  }


  @JsonProperty(JSON_PROPERTY_S_CHURN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setsChurn(BigDecimal sChurn) {
    this.sChurn = sChurn;
  }


  public StableDiffusionProcessingImg2Img sTmax(BigDecimal sTmax) {
    
    this.sTmax = sTmax;
    return this;
  }

   /**
   * Get sTmax
   * @return sTmax
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_S_TMAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getsTmax() {
    return sTmax;
  }


  @JsonProperty(JSON_PROPERTY_S_TMAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setsTmax(BigDecimal sTmax) {
    this.sTmax = sTmax;
  }


  public StableDiffusionProcessingImg2Img sTmin(BigDecimal sTmin) {
    
    this.sTmin = sTmin;
    return this;
  }

   /**
   * Get sTmin
   * @return sTmin
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_S_TMIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getsTmin() {
    return sTmin;
  }


  @JsonProperty(JSON_PROPERTY_S_TMIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setsTmin(BigDecimal sTmin) {
    this.sTmin = sTmin;
  }


  public StableDiffusionProcessingImg2Img sNoise(BigDecimal sNoise) {
    
    this.sNoise = sNoise;
    return this;
  }

   /**
   * Get sNoise
   * @return sNoise
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_S_NOISE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getsNoise() {
    return sNoise;
  }


  @JsonProperty(JSON_PROPERTY_S_NOISE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setsNoise(BigDecimal sNoise) {
    this.sNoise = sNoise;
  }


  public StableDiffusionProcessingImg2Img overrideSettings(Object overrideSettings) {
    
    this.overrideSettings = overrideSettings;
    return this;
  }

   /**
   * Get overrideSettings
   * @return overrideSettings
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OVERRIDE_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getOverrideSettings() {
    return overrideSettings;
  }


  @JsonProperty(JSON_PROPERTY_OVERRIDE_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOverrideSettings(Object overrideSettings) {
    this.overrideSettings = overrideSettings;
  }


  public StableDiffusionProcessingImg2Img overrideSettingsRestoreAfterwards(Boolean overrideSettingsRestoreAfterwards) {
    
    this.overrideSettingsRestoreAfterwards = overrideSettingsRestoreAfterwards;
    return this;
  }

   /**
   * Get overrideSettingsRestoreAfterwards
   * @return overrideSettingsRestoreAfterwards
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OVERRIDE_SETTINGS_RESTORE_AFTERWARDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOverrideSettingsRestoreAfterwards() {
    return overrideSettingsRestoreAfterwards;
  }


  @JsonProperty(JSON_PROPERTY_OVERRIDE_SETTINGS_RESTORE_AFTERWARDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOverrideSettingsRestoreAfterwards(Boolean overrideSettingsRestoreAfterwards) {
    this.overrideSettingsRestoreAfterwards = overrideSettingsRestoreAfterwards;
  }


  public StableDiffusionProcessingImg2Img refinerCheckpoint(String refinerCheckpoint) {
    
    this.refinerCheckpoint = refinerCheckpoint;
    return this;
  }

   /**
   * Get refinerCheckpoint
   * @return refinerCheckpoint
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFINER_CHECKPOINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRefinerCheckpoint() {
    return refinerCheckpoint;
  }


  @JsonProperty(JSON_PROPERTY_REFINER_CHECKPOINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefinerCheckpoint(String refinerCheckpoint) {
    this.refinerCheckpoint = refinerCheckpoint;
  }


  public StableDiffusionProcessingImg2Img refinerSwitchAt(BigDecimal refinerSwitchAt) {
    
    this.refinerSwitchAt = refinerSwitchAt;
    return this;
  }

   /**
   * Get refinerSwitchAt
   * @return refinerSwitchAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFINER_SWITCH_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getRefinerSwitchAt() {
    return refinerSwitchAt;
  }


  @JsonProperty(JSON_PROPERTY_REFINER_SWITCH_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefinerSwitchAt(BigDecimal refinerSwitchAt) {
    this.refinerSwitchAt = refinerSwitchAt;
  }


  public StableDiffusionProcessingImg2Img disableExtraNetworks(Boolean disableExtraNetworks) {
    
    this.disableExtraNetworks = disableExtraNetworks;
    return this;
  }

   /**
   * Get disableExtraNetworks
   * @return disableExtraNetworks
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISABLE_EXTRA_NETWORKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisableExtraNetworks() {
    return disableExtraNetworks;
  }


  @JsonProperty(JSON_PROPERTY_DISABLE_EXTRA_NETWORKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisableExtraNetworks(Boolean disableExtraNetworks) {
    this.disableExtraNetworks = disableExtraNetworks;
  }


  public StableDiffusionProcessingImg2Img comments(Object comments) {
    
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getComments() {
    return comments;
  }


  @JsonProperty(JSON_PROPERTY_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComments(Object comments) {
    this.comments = comments;
  }


  public StableDiffusionProcessingImg2Img initImages(List<Object> initImages) {
    
    this.initImages = initImages;
    return this;
  }

  public StableDiffusionProcessingImg2Img addInitImagesItem(Object initImagesItem) {
    if (this.initImages == null) {
      this.initImages = new ArrayList<>();
    }
    this.initImages.add(initImagesItem);
    return this;
  }

   /**
   * Get initImages
   * @return initImages
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INIT_IMAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getInitImages() {
    return initImages;
  }


  @JsonProperty(JSON_PROPERTY_INIT_IMAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInitImages(List<Object> initImages) {
    this.initImages = initImages;
  }


  public StableDiffusionProcessingImg2Img resizeMode(Integer resizeMode) {
    
    this.resizeMode = resizeMode;
    return this;
  }

   /**
   * Get resizeMode
   * @return resizeMode
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESIZE_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getResizeMode() {
    return resizeMode;
  }


  @JsonProperty(JSON_PROPERTY_RESIZE_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResizeMode(Integer resizeMode) {
    this.resizeMode = resizeMode;
  }


  public StableDiffusionProcessingImg2Img imageCfgScale(BigDecimal imageCfgScale) {
    
    this.imageCfgScale = imageCfgScale;
    return this;
  }

   /**
   * Get imageCfgScale
   * @return imageCfgScale
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IMAGE_CFG_SCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getImageCfgScale() {
    return imageCfgScale;
  }


  @JsonProperty(JSON_PROPERTY_IMAGE_CFG_SCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImageCfgScale(BigDecimal imageCfgScale) {
    this.imageCfgScale = imageCfgScale;
  }


  public StableDiffusionProcessingImg2Img mask(String mask) {
    
    this.mask = mask;
    return this;
  }

   /**
   * Get mask
   * @return mask
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MASK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMask() {
    return mask;
  }


  @JsonProperty(JSON_PROPERTY_MASK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMask(String mask) {
    this.mask = mask;
  }


  public StableDiffusionProcessingImg2Img maskBlurX(Integer maskBlurX) {
    
    this.maskBlurX = maskBlurX;
    return this;
  }

   /**
   * Get maskBlurX
   * @return maskBlurX
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MASK_BLUR_X)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaskBlurX() {
    return maskBlurX;
  }


  @JsonProperty(JSON_PROPERTY_MASK_BLUR_X)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaskBlurX(Integer maskBlurX) {
    this.maskBlurX = maskBlurX;
  }


  public StableDiffusionProcessingImg2Img maskBlurY(Integer maskBlurY) {
    
    this.maskBlurY = maskBlurY;
    return this;
  }

   /**
   * Get maskBlurY
   * @return maskBlurY
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MASK_BLUR_Y)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaskBlurY() {
    return maskBlurY;
  }


  @JsonProperty(JSON_PROPERTY_MASK_BLUR_Y)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaskBlurY(Integer maskBlurY) {
    this.maskBlurY = maskBlurY;
  }


  public StableDiffusionProcessingImg2Img maskBlur(Integer maskBlur) {
    
    this.maskBlur = maskBlur;
    return this;
  }

   /**
   * Get maskBlur
   * @return maskBlur
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MASK_BLUR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaskBlur() {
    return maskBlur;
  }


  @JsonProperty(JSON_PROPERTY_MASK_BLUR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaskBlur(Integer maskBlur) {
    this.maskBlur = maskBlur;
  }


  public StableDiffusionProcessingImg2Img inpaintingFill(Integer inpaintingFill) {
    
    this.inpaintingFill = inpaintingFill;
    return this;
  }

   /**
   * Get inpaintingFill
   * @return inpaintingFill
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INPAINTING_FILL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getInpaintingFill() {
    return inpaintingFill;
  }


  @JsonProperty(JSON_PROPERTY_INPAINTING_FILL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInpaintingFill(Integer inpaintingFill) {
    this.inpaintingFill = inpaintingFill;
  }


  public StableDiffusionProcessingImg2Img inpaintFullRes(Boolean inpaintFullRes) {
    
    this.inpaintFullRes = inpaintFullRes;
    return this;
  }

   /**
   * Get inpaintFullRes
   * @return inpaintFullRes
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INPAINT_FULL_RES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getInpaintFullRes() {
    return inpaintFullRes;
  }


  @JsonProperty(JSON_PROPERTY_INPAINT_FULL_RES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInpaintFullRes(Boolean inpaintFullRes) {
    this.inpaintFullRes = inpaintFullRes;
  }


  public StableDiffusionProcessingImg2Img inpaintFullResPadding(Integer inpaintFullResPadding) {
    
    this.inpaintFullResPadding = inpaintFullResPadding;
    return this;
  }

   /**
   * Get inpaintFullResPadding
   * @return inpaintFullResPadding
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INPAINT_FULL_RES_PADDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getInpaintFullResPadding() {
    return inpaintFullResPadding;
  }


  @JsonProperty(JSON_PROPERTY_INPAINT_FULL_RES_PADDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInpaintFullResPadding(Integer inpaintFullResPadding) {
    this.inpaintFullResPadding = inpaintFullResPadding;
  }


  public StableDiffusionProcessingImg2Img inpaintingMaskInvert(Integer inpaintingMaskInvert) {
    
    this.inpaintingMaskInvert = inpaintingMaskInvert;
    return this;
  }

   /**
   * Get inpaintingMaskInvert
   * @return inpaintingMaskInvert
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INPAINTING_MASK_INVERT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getInpaintingMaskInvert() {
    return inpaintingMaskInvert;
  }


  @JsonProperty(JSON_PROPERTY_INPAINTING_MASK_INVERT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInpaintingMaskInvert(Integer inpaintingMaskInvert) {
    this.inpaintingMaskInvert = inpaintingMaskInvert;
  }


  public StableDiffusionProcessingImg2Img initialNoiseMultiplier(BigDecimal initialNoiseMultiplier) {
    
    this.initialNoiseMultiplier = initialNoiseMultiplier;
    return this;
  }

   /**
   * Get initialNoiseMultiplier
   * @return initialNoiseMultiplier
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INITIAL_NOISE_MULTIPLIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getInitialNoiseMultiplier() {
    return initialNoiseMultiplier;
  }


  @JsonProperty(JSON_PROPERTY_INITIAL_NOISE_MULTIPLIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInitialNoiseMultiplier(BigDecimal initialNoiseMultiplier) {
    this.initialNoiseMultiplier = initialNoiseMultiplier;
  }


  public StableDiffusionProcessingImg2Img latentMask(String latentMask) {
    
    this.latentMask = latentMask;
    return this;
  }

   /**
   * Get latentMask
   * @return latentMask
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LATENT_MASK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLatentMask() {
    return latentMask;
  }


  @JsonProperty(JSON_PROPERTY_LATENT_MASK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatentMask(String latentMask) {
    this.latentMask = latentMask;
  }


  public StableDiffusionProcessingImg2Img samplerIndex(String samplerIndex) {
    
    this.samplerIndex = samplerIndex;
    return this;
  }

   /**
   * Get samplerIndex
   * @return samplerIndex
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SAMPLER_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSamplerIndex() {
    return samplerIndex;
  }


  @JsonProperty(JSON_PROPERTY_SAMPLER_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSamplerIndex(String samplerIndex) {
    this.samplerIndex = samplerIndex;
  }


  public StableDiffusionProcessingImg2Img includeInitImages(Boolean includeInitImages) {
    
    this.includeInitImages = includeInitImages;
    return this;
  }

   /**
   * Get includeInitImages
   * @return includeInitImages
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INCLUDE_INIT_IMAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIncludeInitImages() {
    return includeInitImages;
  }


  @JsonProperty(JSON_PROPERTY_INCLUDE_INIT_IMAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncludeInitImages(Boolean includeInitImages) {
    this.includeInitImages = includeInitImages;
  }


  public StableDiffusionProcessingImg2Img scriptName(String scriptName) {
    
    this.scriptName = scriptName;
    return this;
  }

   /**
   * Get scriptName
   * @return scriptName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCRIPT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getScriptName() {
    return scriptName;
  }


  @JsonProperty(JSON_PROPERTY_SCRIPT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScriptName(String scriptName) {
    this.scriptName = scriptName;
  }


  public StableDiffusionProcessingImg2Img scriptArgs(List<Object> scriptArgs) {
    
    this.scriptArgs = scriptArgs;
    return this;
  }

  public StableDiffusionProcessingImg2Img addScriptArgsItem(Object scriptArgsItem) {
    if (this.scriptArgs == null) {
      this.scriptArgs = new ArrayList<>();
    }
    this.scriptArgs.add(scriptArgsItem);
    return this;
  }

   /**
   * Get scriptArgs
   * @return scriptArgs
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCRIPT_ARGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getScriptArgs() {
    return scriptArgs;
  }


  @JsonProperty(JSON_PROPERTY_SCRIPT_ARGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScriptArgs(List<Object> scriptArgs) {
    this.scriptArgs = scriptArgs;
  }


  public StableDiffusionProcessingImg2Img sendImages(Boolean sendImages) {
    
    this.sendImages = sendImages;
    return this;
  }

   /**
   * Get sendImages
   * @return sendImages
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEND_IMAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSendImages() {
    return sendImages;
  }


  @JsonProperty(JSON_PROPERTY_SEND_IMAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSendImages(Boolean sendImages) {
    this.sendImages = sendImages;
  }


  public StableDiffusionProcessingImg2Img saveImages(Boolean saveImages) {
    
    this.saveImages = saveImages;
    return this;
  }

   /**
   * Get saveImages
   * @return saveImages
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SAVE_IMAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSaveImages() {
    return saveImages;
  }


  @JsonProperty(JSON_PROPERTY_SAVE_IMAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSaveImages(Boolean saveImages) {
    this.saveImages = saveImages;
  }


  public StableDiffusionProcessingImg2Img alwaysonScripts(Object alwaysonScripts) {
    
    this.alwaysonScripts = alwaysonScripts;
    return this;
  }

   /**
   * Get alwaysonScripts
   * @return alwaysonScripts
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALWAYSON_SCRIPTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getAlwaysonScripts() {
    return alwaysonScripts;
  }


  @JsonProperty(JSON_PROPERTY_ALWAYSON_SCRIPTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlwaysonScripts(Object alwaysonScripts) {
    this.alwaysonScripts = alwaysonScripts;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StableDiffusionProcessingImg2Img stableDiffusionProcessingImg2Img = (StableDiffusionProcessingImg2Img) o;
    return Objects.equals(this.prompt, stableDiffusionProcessingImg2Img.prompt) &&
        Objects.equals(this.negativePrompt, stableDiffusionProcessingImg2Img.negativePrompt) &&
        Objects.equals(this.styles, stableDiffusionProcessingImg2Img.styles) &&
        Objects.equals(this.seed, stableDiffusionProcessingImg2Img.seed) &&
        Objects.equals(this.subseed, stableDiffusionProcessingImg2Img.subseed) &&
        Objects.equals(this.subseedStrength, stableDiffusionProcessingImg2Img.subseedStrength) &&
        Objects.equals(this.seedResizeFromH, stableDiffusionProcessingImg2Img.seedResizeFromH) &&
        Objects.equals(this.seedResizeFromW, stableDiffusionProcessingImg2Img.seedResizeFromW) &&
        Objects.equals(this.samplerName, stableDiffusionProcessingImg2Img.samplerName) &&
        Objects.equals(this.batchSize, stableDiffusionProcessingImg2Img.batchSize) &&
        Objects.equals(this.nIter, stableDiffusionProcessingImg2Img.nIter) &&
        Objects.equals(this.steps, stableDiffusionProcessingImg2Img.steps) &&
        Objects.equals(this.cfgScale, stableDiffusionProcessingImg2Img.cfgScale) &&
        Objects.equals(this.width, stableDiffusionProcessingImg2Img.width) &&
        Objects.equals(this.height, stableDiffusionProcessingImg2Img.height) &&
        Objects.equals(this.restoreFaces, stableDiffusionProcessingImg2Img.restoreFaces) &&
        Objects.equals(this.tiling, stableDiffusionProcessingImg2Img.tiling) &&
        Objects.equals(this.doNotSaveSamples, stableDiffusionProcessingImg2Img.doNotSaveSamples) &&
        Objects.equals(this.doNotSaveGrid, stableDiffusionProcessingImg2Img.doNotSaveGrid) &&
        Objects.equals(this.eta, stableDiffusionProcessingImg2Img.eta) &&
        Objects.equals(this.denoisingStrength, stableDiffusionProcessingImg2Img.denoisingStrength) &&
        Objects.equals(this.sMinUncond, stableDiffusionProcessingImg2Img.sMinUncond) &&
        Objects.equals(this.sChurn, stableDiffusionProcessingImg2Img.sChurn) &&
        Objects.equals(this.sTmax, stableDiffusionProcessingImg2Img.sTmax) &&
        Objects.equals(this.sTmin, stableDiffusionProcessingImg2Img.sTmin) &&
        Objects.equals(this.sNoise, stableDiffusionProcessingImg2Img.sNoise) &&
        Objects.equals(this.overrideSettings, stableDiffusionProcessingImg2Img.overrideSettings) &&
        Objects.equals(this.overrideSettingsRestoreAfterwards, stableDiffusionProcessingImg2Img.overrideSettingsRestoreAfterwards) &&
        Objects.equals(this.refinerCheckpoint, stableDiffusionProcessingImg2Img.refinerCheckpoint) &&
        Objects.equals(this.refinerSwitchAt, stableDiffusionProcessingImg2Img.refinerSwitchAt) &&
        Objects.equals(this.disableExtraNetworks, stableDiffusionProcessingImg2Img.disableExtraNetworks) &&
        Objects.equals(this.comments, stableDiffusionProcessingImg2Img.comments) &&
        Objects.equals(this.initImages, stableDiffusionProcessingImg2Img.initImages) &&
        Objects.equals(this.resizeMode, stableDiffusionProcessingImg2Img.resizeMode) &&
        Objects.equals(this.imageCfgScale, stableDiffusionProcessingImg2Img.imageCfgScale) &&
        Objects.equals(this.mask, stableDiffusionProcessingImg2Img.mask) &&
        Objects.equals(this.maskBlurX, stableDiffusionProcessingImg2Img.maskBlurX) &&
        Objects.equals(this.maskBlurY, stableDiffusionProcessingImg2Img.maskBlurY) &&
        Objects.equals(this.maskBlur, stableDiffusionProcessingImg2Img.maskBlur) &&
        Objects.equals(this.inpaintingFill, stableDiffusionProcessingImg2Img.inpaintingFill) &&
        Objects.equals(this.inpaintFullRes, stableDiffusionProcessingImg2Img.inpaintFullRes) &&
        Objects.equals(this.inpaintFullResPadding, stableDiffusionProcessingImg2Img.inpaintFullResPadding) &&
        Objects.equals(this.inpaintingMaskInvert, stableDiffusionProcessingImg2Img.inpaintingMaskInvert) &&
        Objects.equals(this.initialNoiseMultiplier, stableDiffusionProcessingImg2Img.initialNoiseMultiplier) &&
        Objects.equals(this.latentMask, stableDiffusionProcessingImg2Img.latentMask) &&
        Objects.equals(this.samplerIndex, stableDiffusionProcessingImg2Img.samplerIndex) &&
        Objects.equals(this.includeInitImages, stableDiffusionProcessingImg2Img.includeInitImages) &&
        Objects.equals(this.scriptName, stableDiffusionProcessingImg2Img.scriptName) &&
        Objects.equals(this.scriptArgs, stableDiffusionProcessingImg2Img.scriptArgs) &&
        Objects.equals(this.sendImages, stableDiffusionProcessingImg2Img.sendImages) &&
        Objects.equals(this.saveImages, stableDiffusionProcessingImg2Img.saveImages) &&
        Objects.equals(this.alwaysonScripts, stableDiffusionProcessingImg2Img.alwaysonScripts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prompt, negativePrompt, styles, seed, subseed, subseedStrength, seedResizeFromH, seedResizeFromW, samplerName, batchSize, nIter, steps, cfgScale, width, height, restoreFaces, tiling, doNotSaveSamples, doNotSaveGrid, eta, denoisingStrength, sMinUncond, sChurn, sTmax, sTmin, sNoise, overrideSettings, overrideSettingsRestoreAfterwards, refinerCheckpoint, refinerSwitchAt, disableExtraNetworks, comments, initImages, resizeMode, imageCfgScale, mask, maskBlurX, maskBlurY, maskBlur, inpaintingFill, inpaintFullRes, inpaintFullResPadding, inpaintingMaskInvert, initialNoiseMultiplier, latentMask, samplerIndex, includeInitImages, scriptName, scriptArgs, sendImages, saveImages, alwaysonScripts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StableDiffusionProcessingImg2Img {\n");
    sb.append("    prompt: ").append(toIndentedString(prompt)).append("\n");
    sb.append("    negativePrompt: ").append(toIndentedString(negativePrompt)).append("\n");
    sb.append("    styles: ").append(toIndentedString(styles)).append("\n");
    sb.append("    seed: ").append(toIndentedString(seed)).append("\n");
    sb.append("    subseed: ").append(toIndentedString(subseed)).append("\n");
    sb.append("    subseedStrength: ").append(toIndentedString(subseedStrength)).append("\n");
    sb.append("    seedResizeFromH: ").append(toIndentedString(seedResizeFromH)).append("\n");
    sb.append("    seedResizeFromW: ").append(toIndentedString(seedResizeFromW)).append("\n");
    sb.append("    samplerName: ").append(toIndentedString(samplerName)).append("\n");
    sb.append("    batchSize: ").append(toIndentedString(batchSize)).append("\n");
    sb.append("    nIter: ").append(toIndentedString(nIter)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("    cfgScale: ").append(toIndentedString(cfgScale)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    restoreFaces: ").append(toIndentedString(restoreFaces)).append("\n");
    sb.append("    tiling: ").append(toIndentedString(tiling)).append("\n");
    sb.append("    doNotSaveSamples: ").append(toIndentedString(doNotSaveSamples)).append("\n");
    sb.append("    doNotSaveGrid: ").append(toIndentedString(doNotSaveGrid)).append("\n");
    sb.append("    eta: ").append(toIndentedString(eta)).append("\n");
    sb.append("    denoisingStrength: ").append(toIndentedString(denoisingStrength)).append("\n");
    sb.append("    sMinUncond: ").append(toIndentedString(sMinUncond)).append("\n");
    sb.append("    sChurn: ").append(toIndentedString(sChurn)).append("\n");
    sb.append("    sTmax: ").append(toIndentedString(sTmax)).append("\n");
    sb.append("    sTmin: ").append(toIndentedString(sTmin)).append("\n");
    sb.append("    sNoise: ").append(toIndentedString(sNoise)).append("\n");
    sb.append("    overrideSettings: ").append(toIndentedString(overrideSettings)).append("\n");
    sb.append("    overrideSettingsRestoreAfterwards: ").append(toIndentedString(overrideSettingsRestoreAfterwards)).append("\n");
    sb.append("    refinerCheckpoint: ").append(toIndentedString(refinerCheckpoint)).append("\n");
    sb.append("    refinerSwitchAt: ").append(toIndentedString(refinerSwitchAt)).append("\n");
    sb.append("    disableExtraNetworks: ").append(toIndentedString(disableExtraNetworks)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    initImages: ").append(toIndentedString(initImages)).append("\n");
    sb.append("    resizeMode: ").append(toIndentedString(resizeMode)).append("\n");
    sb.append("    imageCfgScale: ").append(toIndentedString(imageCfgScale)).append("\n");
    sb.append("    mask: ").append(toIndentedString(mask)).append("\n");
    sb.append("    maskBlurX: ").append(toIndentedString(maskBlurX)).append("\n");
    sb.append("    maskBlurY: ").append(toIndentedString(maskBlurY)).append("\n");
    sb.append("    maskBlur: ").append(toIndentedString(maskBlur)).append("\n");
    sb.append("    inpaintingFill: ").append(toIndentedString(inpaintingFill)).append("\n");
    sb.append("    inpaintFullRes: ").append(toIndentedString(inpaintFullRes)).append("\n");
    sb.append("    inpaintFullResPadding: ").append(toIndentedString(inpaintFullResPadding)).append("\n");
    sb.append("    inpaintingMaskInvert: ").append(toIndentedString(inpaintingMaskInvert)).append("\n");
    sb.append("    initialNoiseMultiplier: ").append(toIndentedString(initialNoiseMultiplier)).append("\n");
    sb.append("    latentMask: ").append(toIndentedString(latentMask)).append("\n");
    sb.append("    samplerIndex: ").append(toIndentedString(samplerIndex)).append("\n");
    sb.append("    includeInitImages: ").append(toIndentedString(includeInitImages)).append("\n");
    sb.append("    scriptName: ").append(toIndentedString(scriptName)).append("\n");
    sb.append("    scriptArgs: ").append(toIndentedString(scriptArgs)).append("\n");
    sb.append("    sendImages: ").append(toIndentedString(sendImages)).append("\n");
    sb.append("    saveImages: ").append(toIndentedString(saveImages)).append("\n");
    sb.append("    alwaysonScripts: ").append(toIndentedString(alwaysonScripts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

