/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.automatic.webui.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for EmbeddingItem
 */
public class EmbeddingItemTest {
    private final EmbeddingItem model = new EmbeddingItem();

    /**
     * Model tests for EmbeddingItem
     */
    @Test
    public void testEmbeddingItem() {
        // TODO: test EmbeddingItem
    }

    /**
     * Test the property 'step'
     */
    @Test
    public void stepTest() {
        // TODO: test step
    }

    /**
     * Test the property 'sdCheckpoint'
     */
    @Test
    public void sdCheckpointTest() {
        // TODO: test sdCheckpoint
    }

    /**
     * Test the property 'sdCheckpointName'
     */
    @Test
    public void sdCheckpointNameTest() {
        // TODO: test sdCheckpointName
    }

    /**
     * Test the property 'shape'
     */
    @Test
    public void shapeTest() {
        // TODO: test shape
    }

    /**
     * Test the property 'vectors'
     */
    @Test
    public void vectorsTest() {
        // TODO: test vectors
    }

}
