/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.automatic.webui.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for Estimation
 */
public class EstimationTest {
    private final Estimation model = new Estimation();

    /**
     * Model tests for Estimation
     */
    @Test
    public void testEstimation() {
        // TODO: test Estimation
    }

    /**
     * Test the property 'msg'
     */
    @Test
    public void msgTest() {
        // TODO: test msg
    }

    /**
     * Test the property 'rank'
     */
    @Test
    public void rankTest() {
        // TODO: test rank
    }

    /**
     * Test the property 'queueSize'
     */
    @Test
    public void queueSizeTest() {
        // TODO: test queueSize
    }

    /**
     * Test the property 'avgEventProcessTime'
     */
    @Test
    public void avgEventProcessTimeTest() {
        // TODO: test avgEventProcessTime
    }

    /**
     * Test the property 'avgEventConcurrentProcessTime'
     */
    @Test
    public void avgEventConcurrentProcessTimeTest() {
        // TODO: test avgEventConcurrentProcessTime
    }

    /**
     * Test the property 'rankEta'
     */
    @Test
    public void rankEtaTest() {
        // TODO: test rankEta
    }

    /**
     * Test the property 'queueEta'
     */
    @Test
    public void queueEtaTest() {
        // TODO: test queueEta
    }

}
