/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.automatic.webui.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ExtrasBatchImagesResponse
 */
public class ExtrasBatchImagesResponseTest {
    private final ExtrasBatchImagesResponse model = new ExtrasBatchImagesResponse();

    /**
     * Model tests for ExtrasBatchImagesResponse
     */
    @Test
    public void testExtrasBatchImagesResponse() {
        // TODO: test ExtrasBatchImagesResponse
    }

    /**
     * Test the property 'htmlInfo'
     */
    @Test
    public void htmlInfoTest() {
        // TODO: test htmlInfo
    }

    /**
     * Test the property 'images'
     */
    @Test
    public void imagesTest() {
        // TODO: test images
    }

}
