/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.automatic.webui.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import team.polytech.automatic.webui.model.FileData;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ExtrasBatchImagesRequest
 */
public class ExtrasBatchImagesRequestTest {
    private final ExtrasBatchImagesRequest model = new ExtrasBatchImagesRequest();

    /**
     * Model tests for ExtrasBatchImagesRequest
     */
    @Test
    public void testExtrasBatchImagesRequest() {
        // TODO: test ExtrasBatchImagesRequest
    }

    /**
     * Test the property 'resizeMode'
     */
    @Test
    public void resizeModeTest() {
        // TODO: test resizeMode
    }

    /**
     * Test the property 'showExtrasResults'
     */
    @Test
    public void showExtrasResultsTest() {
        // TODO: test showExtrasResults
    }

    /**
     * Test the property 'gfpganVisibility'
     */
    @Test
    public void gfpganVisibilityTest() {
        // TODO: test gfpganVisibility
    }

    /**
     * Test the property 'codeformerVisibility'
     */
    @Test
    public void codeformerVisibilityTest() {
        // TODO: test codeformerVisibility
    }

    /**
     * Test the property 'codeformerWeight'
     */
    @Test
    public void codeformerWeightTest() {
        // TODO: test codeformerWeight
    }

    /**
     * Test the property 'upscalingResize'
     */
    @Test
    public void upscalingResizeTest() {
        // TODO: test upscalingResize
    }

    /**
     * Test the property 'upscalingResizeW'
     */
    @Test
    public void upscalingResizeWTest() {
        // TODO: test upscalingResizeW
    }

    /**
     * Test the property 'upscalingResizeH'
     */
    @Test
    public void upscalingResizeHTest() {
        // TODO: test upscalingResizeH
    }

    /**
     * Test the property 'upscalingCrop'
     */
    @Test
    public void upscalingCropTest() {
        // TODO: test upscalingCrop
    }

    /**
     * Test the property 'upscaler1'
     */
    @Test
    public void upscaler1Test() {
        // TODO: test upscaler1
    }

    /**
     * Test the property 'upscaler2'
     */
    @Test
    public void upscaler2Test() {
        // TODO: test upscaler2
    }

    /**
     * Test the property 'extrasUpscaler2Visibility'
     */
    @Test
    public void extrasUpscaler2VisibilityTest() {
        // TODO: test extrasUpscaler2Visibility
    }

    /**
     * Test the property 'upscaleFirst'
     */
    @Test
    public void upscaleFirstTest() {
        // TODO: test upscaleFirst
    }

    /**
     * Test the property 'imageList'
     */
    @Test
    public void imageListTest() {
        // TODO: test imageList
    }

}
