/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.automatic.webui.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ModulesProgressProgressResponse
 */
public class ModulesProgressProgressResponseTest {
    private final ModulesProgressProgressResponse model = new ModulesProgressProgressResponse();

    /**
     * Model tests for ModulesProgressProgressResponse
     */
    @Test
    public void testModulesProgressProgressResponse() {
        // TODO: test ModulesProgressProgressResponse
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'queued'
     */
    @Test
    public void queuedTest() {
        // TODO: test queued
    }

    /**
     * Test the property 'completed'
     */
    @Test
    public void completedTest() {
        // TODO: test completed
    }

    /**
     * Test the property 'progress'
     */
    @Test
    public void progressTest() {
        // TODO: test progress
    }

    /**
     * Test the property 'eta'
     */
    @Test
    public void etaTest() {
        // TODO: test eta
    }

    /**
     * Test the property 'livePreview'
     */
    @Test
    public void livePreviewTest() {
        // TODO: test livePreview
    }

    /**
     * Test the property 'idLivePreview'
     */
    @Test
    public void idLivePreviewTest() {
        // TODO: test idLivePreview
    }

    /**
     * Test the property 'textinfo'
     */
    @Test
    public void textinfoTest() {
        // TODO: test textinfo
    }

}
