/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.automatic.webui.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ModulesApiModelsProgressResponse
 */
public class ModulesApiModelsProgressResponseTest {
    private final ModulesApiModelsProgressResponse model = new ModulesApiModelsProgressResponse();

    /**
     * Model tests for ModulesApiModelsProgressResponse
     */
    @Test
    public void testModulesApiModelsProgressResponse() {
        // TODO: test ModulesApiModelsProgressResponse
    }

    /**
     * Test the property 'progress'
     */
    @Test
    public void progressTest() {
        // TODO: test progress
    }

    /**
     * Test the property 'etaRelative'
     */
    @Test
    public void etaRelativeTest() {
        // TODO: test etaRelative
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'currentImage'
     */
    @Test
    public void currentImageTest() {
        // TODO: test currentImage
    }

    /**
     * Test the property 'textinfo'
     */
    @Test
    public void textinfoTest() {
        // TODO: test textinfo
    }

}
