/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.automatic.webui.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import team.polytech.automatic.webui.model.Request;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for PredictBody
 */
public class PredictBodyTest {
    private final PredictBody model = new PredictBody();

    /**
     * Model tests for PredictBody
     */
    @Test
    public void testPredictBody() {
        // TODO: test PredictBody
    }

    /**
     * Test the property 'sessionHash'
     */
    @Test
    public void sessionHashTest() {
        // TODO: test sessionHash
    }

    /**
     * Test the property 'eventId'
     */
    @Test
    public void eventIdTest() {
        // TODO: test eventId
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'eventData'
     */
    @Test
    public void eventDataTest() {
        // TODO: test eventData
    }

    /**
     * Test the property 'fnIndex'
     */
    @Test
    public void fnIndexTest() {
        // TODO: test fnIndex
    }

    /**
     * Test the property 'batched'
     */
    @Test
    public void batchedTest() {
        // TODO: test batched
    }

    /**
     * Test the property 'request'
     */
    @Test
    public void requestTest() {
        // TODO: test request
    }

}
