/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.automatic.webui.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ProgressRequest
 */
public class ProgressRequestTest {
    private final ProgressRequest model = new ProgressRequest();

    /**
     * Model tests for ProgressRequest
     */
    @Test
    public void testProgressRequest() {
        // TODO: test ProgressRequest
    }

    /**
     * Test the property 'idTask'
     */
    @Test
    public void idTaskTest() {
        // TODO: test idTask
    }

    /**
     * Test the property 'idLivePreview'
     */
    @Test
    public void idLivePreviewTest() {
        // TODO: test idLivePreview
    }

    /**
     * Test the property 'livePreview'
     */
    @Test
    public void livePreviewTest() {
        // TODO: test livePreview
    }

}
