/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.automatic.webui.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ScriptsList
 */
public class ScriptsListTest {
    private final ScriptsList model = new ScriptsList();

    /**
     * Model tests for ScriptsList
     */
    @Test
    public void testScriptsList() {
        // TODO: test ScriptsList
    }

    /**
     * Test the property 'txt2img'
     */
    @Test
    public void txt2imgTest() {
        // TODO: test txt2img
    }

    /**
     * Test the property 'img2img'
     */
    @Test
    public void img2imgTest() {
        // TODO: test img2img
    }

}
