/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.automatic.webui.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import team.polytech.automatic.webui.model.ScriptArg;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ScriptInfo
 */
public class ScriptInfoTest {
    private final ScriptInfo model = new ScriptInfo();

    /**
     * Model tests for ScriptInfo
     */
    @Test
    public void testScriptInfo() {
        // TODO: test ScriptInfo
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'isAlwayson'
     */
    @Test
    public void isAlwaysonTest() {
        // TODO: test isAlwayson
    }

    /**
     * Test the property 'isImg2img'
     */
    @Test
    public void isImg2imgTest() {
        // TODO: test isImg2img
    }

    /**
     * Test the property 'args'
     */
    @Test
    public void argsTest() {
        // TODO: test args
    }

}
