/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.automatic.webui.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for StableDiffusionProcessingImg2Img
 */
public class StableDiffusionProcessingImg2ImgTest {
    private final StableDiffusionProcessingImg2Img model = new StableDiffusionProcessingImg2Img();

    /**
     * Model tests for StableDiffusionProcessingImg2Img
     */
    @Test
    public void testStableDiffusionProcessingImg2Img() {
        // TODO: test StableDiffusionProcessingImg2Img
    }

    /**
     * Test the property 'prompt'
     */
    @Test
    public void promptTest() {
        // TODO: test prompt
    }

    /**
     * Test the property 'negativePrompt'
     */
    @Test
    public void negativePromptTest() {
        // TODO: test negativePrompt
    }

    /**
     * Test the property 'styles'
     */
    @Test
    public void stylesTest() {
        // TODO: test styles
    }

    /**
     * Test the property 'seed'
     */
    @Test
    public void seedTest() {
        // TODO: test seed
    }

    /**
     * Test the property 'subseed'
     */
    @Test
    public void subseedTest() {
        // TODO: test subseed
    }

    /**
     * Test the property 'subseedStrength'
     */
    @Test
    public void subseedStrengthTest() {
        // TODO: test subseedStrength
    }

    /**
     * Test the property 'seedResizeFromH'
     */
    @Test
    public void seedResizeFromHTest() {
        // TODO: test seedResizeFromH
    }

    /**
     * Test the property 'seedResizeFromW'
     */
    @Test
    public void seedResizeFromWTest() {
        // TODO: test seedResizeFromW
    }

    /**
     * Test the property 'samplerName'
     */
    @Test
    public void samplerNameTest() {
        // TODO: test samplerName
    }

    /**
     * Test the property 'batchSize'
     */
    @Test
    public void batchSizeTest() {
        // TODO: test batchSize
    }

    /**
     * Test the property 'nIter'
     */
    @Test
    public void nIterTest() {
        // TODO: test nIter
    }

    /**
     * Test the property 'steps'
     */
    @Test
    public void stepsTest() {
        // TODO: test steps
    }

    /**
     * Test the property 'cfgScale'
     */
    @Test
    public void cfgScaleTest() {
        // TODO: test cfgScale
    }

    /**
     * Test the property 'width'
     */
    @Test
    public void widthTest() {
        // TODO: test width
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'restoreFaces'
     */
    @Test
    public void restoreFacesTest() {
        // TODO: test restoreFaces
    }

    /**
     * Test the property 'tiling'
     */
    @Test
    public void tilingTest() {
        // TODO: test tiling
    }

    /**
     * Test the property 'doNotSaveSamples'
     */
    @Test
    public void doNotSaveSamplesTest() {
        // TODO: test doNotSaveSamples
    }

    /**
     * Test the property 'doNotSaveGrid'
     */
    @Test
    public void doNotSaveGridTest() {
        // TODO: test doNotSaveGrid
    }

    /**
     * Test the property 'eta'
     */
    @Test
    public void etaTest() {
        // TODO: test eta
    }

    /**
     * Test the property 'denoisingStrength'
     */
    @Test
    public void denoisingStrengthTest() {
        // TODO: test denoisingStrength
    }

    /**
     * Test the property 'sMinUncond'
     */
    @Test
    public void sMinUncondTest() {
        // TODO: test sMinUncond
    }

    /**
     * Test the property 'sChurn'
     */
    @Test
    public void sChurnTest() {
        // TODO: test sChurn
    }

    /**
     * Test the property 'sTmax'
     */
    @Test
    public void sTmaxTest() {
        // TODO: test sTmax
    }

    /**
     * Test the property 'sTmin'
     */
    @Test
    public void sTminTest() {
        // TODO: test sTmin
    }

    /**
     * Test the property 'sNoise'
     */
    @Test
    public void sNoiseTest() {
        // TODO: test sNoise
    }

    /**
     * Test the property 'overrideSettings'
     */
    @Test
    public void overrideSettingsTest() {
        // TODO: test overrideSettings
    }

    /**
     * Test the property 'overrideSettingsRestoreAfterwards'
     */
    @Test
    public void overrideSettingsRestoreAfterwardsTest() {
        // TODO: test overrideSettingsRestoreAfterwards
    }

    /**
     * Test the property 'refinerCheckpoint'
     */
    @Test
    public void refinerCheckpointTest() {
        // TODO: test refinerCheckpoint
    }

    /**
     * Test the property 'refinerSwitchAt'
     */
    @Test
    public void refinerSwitchAtTest() {
        // TODO: test refinerSwitchAt
    }

    /**
     * Test the property 'disableExtraNetworks'
     */
    @Test
    public void disableExtraNetworksTest() {
        // TODO: test disableExtraNetworks
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

    /**
     * Test the property 'initImages'
     */
    @Test
    public void initImagesTest() {
        // TODO: test initImages
    }

    /**
     * Test the property 'resizeMode'
     */
    @Test
    public void resizeModeTest() {
        // TODO: test resizeMode
    }

    /**
     * Test the property 'imageCfgScale'
     */
    @Test
    public void imageCfgScaleTest() {
        // TODO: test imageCfgScale
    }

    /**
     * Test the property 'mask'
     */
    @Test
    public void maskTest() {
        // TODO: test mask
    }

    /**
     * Test the property 'maskBlurX'
     */
    @Test
    public void maskBlurXTest() {
        // TODO: test maskBlurX
    }

    /**
     * Test the property 'maskBlurY'
     */
    @Test
    public void maskBlurYTest() {
        // TODO: test maskBlurY
    }

    /**
     * Test the property 'maskBlur'
     */
    @Test
    public void maskBlurTest() {
        // TODO: test maskBlur
    }

    /**
     * Test the property 'inpaintingFill'
     */
    @Test
    public void inpaintingFillTest() {
        // TODO: test inpaintingFill
    }

    /**
     * Test the property 'inpaintFullRes'
     */
    @Test
    public void inpaintFullResTest() {
        // TODO: test inpaintFullRes
    }

    /**
     * Test the property 'inpaintFullResPadding'
     */
    @Test
    public void inpaintFullResPaddingTest() {
        // TODO: test inpaintFullResPadding
    }

    /**
     * Test the property 'inpaintingMaskInvert'
     */
    @Test
    public void inpaintingMaskInvertTest() {
        // TODO: test inpaintingMaskInvert
    }

    /**
     * Test the property 'initialNoiseMultiplier'
     */
    @Test
    public void initialNoiseMultiplierTest() {
        // TODO: test initialNoiseMultiplier
    }

    /**
     * Test the property 'latentMask'
     */
    @Test
    public void latentMaskTest() {
        // TODO: test latentMask
    }

    /**
     * Test the property 'samplerIndex'
     */
    @Test
    public void samplerIndexTest() {
        // TODO: test samplerIndex
    }

    /**
     * Test the property 'includeInitImages'
     */
    @Test
    public void includeInitImagesTest() {
        // TODO: test includeInitImages
    }

    /**
     * Test the property 'scriptName'
     */
    @Test
    public void scriptNameTest() {
        // TODO: test scriptName
    }

    /**
     * Test the property 'scriptArgs'
     */
    @Test
    public void scriptArgsTest() {
        // TODO: test scriptArgs
    }

    /**
     * Test the property 'sendImages'
     */
    @Test
    public void sendImagesTest() {
        // TODO: test sendImages
    }

    /**
     * Test the property 'saveImages'
     */
    @Test
    public void saveImagesTest() {
        // TODO: test saveImages
    }

    /**
     * Test the property 'alwaysonScripts'
     */
    @Test
    public void alwaysonScriptsTest() {
        // TODO: test alwaysonScripts
    }

}
