/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.automatic.webui.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import team.polytech.automatic.webui.model.LocationInner;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ValidationError
 */
public class ValidationErrorTest {
    private final ValidationError model = new ValidationError();

    /**
     * Model tests for ValidationError
     */
    @Test
    public void testValidationError() {
        // TODO: test ValidationError
    }

    /**
     * Test the property 'loc'
     */
    @Test
    public void locTest() {
        // TODO: test loc
    }

    /**
     * Test the property 'msg'
     */
    @Test
    public void msgTest() {
        // TODO: test msg
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
